### PR TITLE
musicxml importer fix

### PR DESCRIPTION
**Pull request by rettinghaus**
This is a quick fix for #521
It resulted in xml directions not connected to mRests.

### CODE REVIEW

**Comment by rettinghaus** [comment]
MusicXML doesn't have explicit full-measure rests, but rests with fermatas. The fermatas are now handled below (like in every other case).

**Comment by lpugin** [comment]
I am not sure the fix changes something with the tempo@startid. Could you double check?

**Comment by rettinghaus** [comment]
Latest develop won't build:
> iohumdrum.cpp:2409:19: error: ‘class vrv::Note’ has no member named ‘SetSVGClass’

Do you have another file to test? The Schubert Ständchen worked fine for me.

**Comment by lpugin** [comment]
Weird. For me the `tempo@startid=#note-0000000728534703` in measure 1 still points to a note in measure 5

```
<?xml version="1.0" encoding="UTF-8"?>
<?xml-model href="http://music-encoding.org/schema/3.0.0/mei-all.rng" type="application/xml" schematypens="http://relaxng.org/ns/structure/1.0"?>
<?xml-model href="http://music-encoding.org/schema/3.0.0/mei-all.rng" type="application/xml" schematypens="http://purl.oclc.org/dsdl/schematron"?>
<mei xmlns="http://www.music-encoding.org/ns/mei" meiversion="3.0.0">
    <meiHead>
        <fileDesc>
            <titleStmt>
                <title />
            </titleStmt>
            <pubStmt></pubStmt>
        </fileDesc>
        <encodingDesc xml:id="encodingdesc-0000000388005363">
            <appInfo xml:id="appinfo-0000001929393582">
                <application xml:id="application-0000000940776482" isodate="2017-03-15T13:09:12" version="0.9.14-dev-73b91e5">
                    <name xml:id="name-0000000472903817">Verovio</name>
                    <p xml:id="p-0000000978775698">Transcoded from MusicXML</p>
                </application>
            </appInfo>
        </encodingDesc>
    </meiHead>
    <music>
        <body>
            <mdiv>
                <score>
                    <scoreDef xml:id="scoredef-0000001524367069">
                        <staffGrp xml:id="staffgrp-0000002087884231">
                            <staffDef xml:id="staffdef-0000001611504799" n="1" clef.shape="G" clef.line="2" key.sig="1f" meter.count="3" meter.unit="4" label="Tenor" lines="5" />
                            <staffGrp xml:id="staffgrp-0000000459721527" label="Piano" symbol="brace" barthru="true">
                                <staffDef xml:id="staffdef-0000001862013238" n="2" clef.shape="G" clef.line="2" key.sig="1f" meter.count="3" meter.unit="4" lines="5" />
                                <staffDef xml:id="staffdef-0000000237606918" n="3" clef.shape="F" clef.line="4" key.sig="1f" meter.count="3" meter.unit="4" lines="5" />
                            </staffGrp>
                        </staffGrp>
                    </scoreDef>
                    <section xml:id="section-0000000062850894">
                        <measure xml:id="measure-0000001150307366" n="1">
                            <staff xml:id="staff-0000001313255531" n="1">
                                <layer xml:id="layer-0000001002751231" n="1">
                                    <mRest xml:id="mrest-0000002073636135" />
                                </layer>
                            </staff>
                            <staff xml:id="staff-0000000720377964" n="2">
                                <layer xml:id="layer-0000001956086258" n="1">
                                    <rest xml:id="rest-0000000560530611" dur="8" />
                                    <chord xml:id="chord-0000001484559987" dur="8" stem.dir="up">
                                        <note xml:id="note-0000000036235457" oct="3" pname="a" />
                                        <note xml:id="note-0000000216512769" oct="4" pname="d" />
                                    </chord>
                                    <beam xml:id="beam-0000000726881931">
                                        <chord xml:id="chord-0000000330722324" dur="8" stem.dir="up">
                                            <note xml:id="note-0000002117925750" oct="4" pname="d" />
                                            <note xml:id="note-0000000999610688" oct="4" pname="f" />
                                        </chord>
                                        <chord xml:id="chord-0000001411780144" dur="8" stem.dir="up">
                                            <note xml:id="note-0000000405588257" oct="3" pname="a" />
                                            <note xml:id="note-0000002050110128" oct="4" pname="d" />
                                        </chord>
                                    </beam>
                                    <beam xml:id="beam-0000001586340190">
                                        <chord xml:id="chord-0000000594794032" dur="8" stem.dir="up">
                                            <note xml:id="note-0000001486164176" oct="4" pname="d" />
                                            <note xml:id="note-0000001728350887" oct="4" pname="f" />
                                        </chord>
                                        <chord xml:id="chord-0000002043488409" dur="8" stem.dir="up">
                                            <note xml:id="note-0000001552247077" oct="3" pname="a" />
                                            <note xml:id="note-0000001253826217" oct="4" pname="d" />
                                        </chord>
                                    </beam>
                                </layer>
                            </staff>
                            <staff xml:id="staff-0000000293087496" n="3">
                                <layer xml:id="layer-0000002032840950" n="5">
                                    <chord xml:id="chord-0000001422581982" dur="2" stem.dir="up">
                                        <note xml:id="note-0000000710822812" oct="2" pname="d" />
                                        <note xml:id="note-0000002120313819" oct="3" pname="d" />
                                    </chord>
                                    <rest xml:id="rest-0000002015511704" dur="4" />
                                </layer>
                            </staff>
                            <tempo xml:id="tempo-0000000517625722" place="above" staff="1" startid="#note-0000000728534703" midi.bpm="102">Mäßig</tempo>
                            <dynam xml:id="dynam-0000001676235932" place="below" staff="2" startid="#rest-0000000560530611">pp</dynam>
                        </measure>
                        
                        <!--- measures 2 to 4 -->
                        
                        <measure xml:id="measure-0000000459504078" n="5">
                            <staff xml:id="staff-0000001553953509" n="1">
                                <layer xml:id="layer-0000000982851549" n="1">
                                    <beam xml:id="beam-0000000425313182">
                                        <tuplet xml:id="tuplet-0000000521486439" num="3" numbase="2" bracket.visible="false">
                                            <note xml:id="note-0000000728534703" dur="8" oct="4" pname="a" stem.dir="up">
                                                <verse xml:id="verse-0000001396947370" n="1">
                                                    <syl xml:id="syl-0000000734097006" con="d" wordpos="i">Lei</syl>
                                                </verse>
                                            </note>
                                            <note xml:id="note-0000000010619817" dur="8" oct="4" pname="b" stem.dir="up">
                                                <accid xml:id="accid-0000001339707604" accid.ges="f" />
                                            </note>
                                            <note xml:id="note-0000001179236949" dur="8" oct="4" pname="a" stem.dir="up">
                                                <verse xml:id="verse-0000000412994434" n="1">
                                                    <syl xml:id="syl-0000000183296423" wordpos="t">se</syl>
                                                </verse>
                                            </note>
                                        </tuplet>
                                    </beam>
                                    <note xml:id="note-0000001883956043" dots="1" dur="4" oct="5" pname="d" stem.dir="down">
                                        <verse xml:id="verse-0000000554067987" n="1">
                                            <syl xml:id="syl-0000001658502005" con="d" wordpos="i">fle</syl>
                                        </verse>
                                    </note>
                                    <note xml:id="note-0000000068097466" dur="8" oct="4" pname="a" stem.dir="up">
                                        <verse xml:id="verse-0000001369769897" n="1">
                                            <syl xml:id="syl-0000000042022955" wordpos="t">hen</syl>
                                        </verse>
                                    </note>
                                </layer>
                            </staff>
                            <staff xml:id="staff-0000000956136844" n="2">
                                <layer xml:id="layer-0000001042063773" n="1">
                                    <rest xml:id="rest-0000001638918094" dur="8" />
                                    <chord xml:id="chord-0000000757838030" dur="8" stem.dir="up">
                                        <note xml:id="note-0000001917756977" oct="3" pname="a" />
                                        <note xml:id="note-0000000758792440" oct="4" pname="d" />
                                    </chord>
                                    <beam xml:id="beam-0000000809795877">
                                        <chord xml:id="chord-0000000803359777" dur="8" stem.dir="up">
                                            <note xml:id="note-0000001262885462" oct="4" pname="d" />
                                            <note xml:id="note-0000001777790986" oct="4" pname="f" />
                                        </chord>
                                        <chord xml:id="chord-0000001229227985" dur="8" stem.dir="up">
                                            <note xml:id="note-0000001428323944" oct="3" pname="a" />
                                            <note xml:id="note-0000001122647366" oct="4" pname="d" />
                                        </chord>
                                    </beam>
                                    <beam xml:id="beam-0000001193026738">
                                        <chord xml:id="chord-0000001808945932" dur="8" stem.dir="up">
                                            <note xml:id="note-0000002140010604" oct="4" pname="d" />
                                            <note xml:id="note-0000000700000490" oct="4" pname="f" />
                                        </chord>
                                        <chord xml:id="chord-0000000447592147" dur="8" stem.dir="up">
                                            <note xml:id="note-0000001443489360" oct="3" pname="a" />
                                            <note xml:id="note-0000000215403173" oct="4" pname="d" />
                                        </chord>
                                    </beam>
                                </layer>
                            </staff>
                            <staff xml:id="staff-0000000539161071" n="3">
                                <layer xml:id="layer-0000001611474524" n="5">
                                    <chord xml:id="chord-0000001435151699" dur="2" stem.dir="up">
                                        <note xml:id="note-0000000627253911" oct="2" pname="d" />
                                        <note xml:id="note-0000000656981758" oct="3" pname="d" />
                                    </chord>
                                    <rest xml:id="rest-0000001815178745" dur="4" />
                                </layer>
                            </staff>
                            <slur xml:id="slur-0000000662449396" startid="#note-0000000728534703" endid="#note-0000000010619817" />
                        </measure>
                    </section>
                </score>
            </mdiv>
        </body>
    </music>
</mei>
```

Build: @craigsapp should merge his fix.

**Comment by rettinghaus** [comment]
Did you by any chance run a cached version? Somehow it makes a difference (on my machine) if I run `verovio `or `./verovio`.
Your version: 0.9.14-dev-73b91e5
My version: 0.9.14-dev-b9937fb

**Comment by craigsapp** [comment]
> Build: @craigsapp should merge his fix.

Should I merge develop-humdrum into develop?  There are other changes in the branch, but none of them should be bad.  Here is the fix which was a move to the new type/class system:

https://github.com/rism-ch/verovio/commit/a046a723d87dcefe62bd0d6a3259d0cb50ab6856

**Comment by lpugin** [comment]
@craigsapp merge it.

@rettinghaus looks good now. Thanks!

image

**Pull request merged**
