### PR TITLE
preserve id on mdiv

### PR DESCRIPTION
**Pull request by rettinghaus**
forgotten or intentional?

### CODE REVIEW

**Comment by rettinghaus** [comment]
Should work with score, too.

**Comment by lpugin** [comment]
Forgotten. Could you fix it for Score and Pages too?

**Comment by rettinghaus** [comment]
Added.
NB: imported `xml:id` from `score` gets lost and is replaced with created id from `pages`.

**Comment by lpugin** [comment]
You can fix this in Pages::ConvertFrom(Score) using Object::SwapUuid

**Comment by rettinghaus** [comment]
Ah yes. Wasn't aware of that function.

**Pull request merged**
