### PR TITLE
basic support for trill elements

### PR DESCRIPTION
**Pull request by rettinghaus**
This commit brings basic support for `<trill>` 

trills

```xml
  <music>
    <body>
      <mdiv>
        <score>
          <scoreDef meter.count="4" meter.unit="4">
            <staffGrp>
              <staffDef clef.shape="G" clef.line="2" n="1" lines="5" />
            </staffGrp>
          </scoreDef>
          <section>
            <measure n="1">
              <staff n="1">
                <layer n="1">
                  <note xml:id="note-000000109362457" dur="2" oct="4" pname="g" stem.dir="up" />
                  <note xml:id="note-000000205693633" dur="2" oct="4" pname="g" stem.dir="up"/>
                </layer>
              </staff>
              <trill staff="1" tstamp="1" color="green" place="below"/>
              <fermata startid="#note-000000205693633" color="purple"/>
              <trill startid="#note-000000205693633" color="blue"/>
            </measure>
          </section>
        </score>
      </mdiv>
    </body>
  </music>
```

### CODE REVIEW

**Comment by lpugin** [comment]
This looks great! Could you look why we have all these file changes in the PR and try to avoid them?

**Comment by rettinghaus** [comment]
ooops! I'll have to merge the latest develop branch. Wait for it!

**Comment by rettinghaus** [comment]
That should clean up the mess!

**Comment by lpugin** [comment]
Perfect!

**Pull request merged**
