### PR TITLE
Container staffGrp brackets and braces

### PR DESCRIPTION
**Pull request by rettinghaus**
Brackets and braces from `<staffGrp>` are now contained within a `<g class="grpSym">` referencing the MEI element `<grpSym>` until it's supported natively.

### CODE REVIEW

**Comment by lpugin** [comment]
Could you provide a description? Thanks

**Comment by rettinghaus** [comment]
Brackets and braces from `<staffGrp>` are now contained within a `<g class="grpSym">` referencing the MEI element `<grpSym>` until it's supported natively.

**Comment by lpugin** [comment]
Thanks. Out of curiosity: why do you need this before it is supported natively?

**Comment by rettinghaus** [comment]
Just thinking it would be nice to make them addressable by CSS.

**Pull request merged**
