### PR TITLE
adds simple check for stem.visible on mensural

### PR DESCRIPTION
**Pull request by rettinghaus**

### CODE REVIEW

**Comment by rettinghaus** [comment]
This adds `@stem.visible` to mensural notation. Adding `stem.visible="false"` to note then addresses #839

**Comment by craigsapp** [comment]
How does this affect stem directions for longs/longas and maximas?  I would prefer that stem directions for these would not be ignored.  That is another issue I was planning on adding after some more study (I may have added it before).

In the following example, notice that the maxima and longa stem directions are ignored:

screen shot 2018-05-05 at 11 47 49 am


Test data:

```xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-model href="http://music-encoding.org/schema/4.0.0/mei-all.rng" type="application/xml" schematypens="http://relaxng.org/ns/structure/1.0"?>
<?xml-model href="http://music-encoding.org/schema/4.0.0/mei-all.rng" type="application/xml" schematypens="http://purl.oclc.org/dsdl/schematron"?>
<mei xmlns="http://www.music-encoding.org/ns/mei" meiversion="4.0.0">
    <meiHead>
        <fileDesc>
            <titleStmt>
                <title />
            </titleStmt>
            <pubStmt />
        </fileDesc>
        <encodingDesc>
            <appInfo>
                <application isodate="2018-05-05T11:47:52" version="2.0.0-dev-686bba6-dirty">
                    <name>Verovio</name>
                    <p>Transcoded from Humdrum</p>
                </application>
            </appInfo>
        </encodingDesc>
        <workDesc>
            <work>
                <titleStmt>
                    <title />
                </titleStmt>
            </work>
        </workDesc>
    </meiHead>
    <music>
        <body>
            <mdiv xml:id="mdiv-0000000401036348">
                <score xml:id="score-0000001599617943">
                    <scoreDef xml:id="scoredef-0000001556573747" midi.bpm="400">
                        <staffGrp xml:id="staffgrp-0000000599948315">
                            <staffDef xml:id="staffdef-0000000388986959" clef.shape="C" clef.line="3" n="1" notationtype="mensural" lines="5">
                                <label xml:id="label-0000001679820293" />
                            </staffDef>
                        </staffGrp>
                    </scoreDef>
                    <section xml:id="section-0000001301081334">
                        <measure xml:id="measure-L3" n="1">
                            <staff xml:id="staff-L3F1N1" n="1">
                                <layer xml:id="layer-L3F1N1" n="1">
                                    <note xml:id="note-L4F1" dur="maxima" oct="4" pname="c" accid.ges="n" />
                                    <note xml:id="note-L5F1" dur="maxima" oct="4" pname="c" stem.dir="up" accid.ges="n" />
                                    <note xml:id="note-L6F1" dur="maxima" oct="4" pname="c" stem.dir="down" accid.ges="n" />
                                </layer>
                            </staff>
                        </measure>
                        <measure xml:id="measure-L7">
                            <staff xml:id="staff-L7F1N1" n="1">
                                <layer xml:id="layer-L7F1N1" n="1">
                                    <note xml:id="note-L8F1" dur="longa" oct="4" pname="c" accid.ges="n" />
                                    <note xml:id="note-L9F1" dur="longa" oct="4" pname="c" stem.dir="up" accid.ges="n" />
                                    <note xml:id="note-L10F1" dur="longa" oct="4" pname="c" stem.dir="down" accid.ges="n" />
                                </layer>
                            </staff>
                        </measure>
                        <measure xml:id="measure-L11" right="end">
                            <staff xml:id="staff-L11F1N1" n="1">
                                <layer xml:id="layer-L11F1N1" n="1">
                                    <note xml:id="note-L12F1" dur="minima" oct="4" pname="c" accid.ges="n" />
                                    <note xml:id="note-L13F1" dur="minima" oct="4" pname="c" stem.dir="up" accid.ges="n" />
                                    <note xml:id="note-L14F1" dur="minima" oct="4" pname="c" stem.dir="down" accid.ges="n" />
                                </layer>
                            </staff>
                        </measure>
                    </section>
                </score>
            </mdiv>
        </body>
    </music>
</mei>
```

The stem directions are also ignored for longs (and maximas) in modern notation (which I think I might already have as an issue):

screen shot 2018-05-05 at 11 49 40 am



```xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-model href="http://music-encoding.org/schema/4.0.0/mei-all.rng" type="application/xml" schematypens="http://relaxng.org/ns/structure/1.0"?>
<?xml-model href="http://music-encoding.org/schema/4.0.0/mei-all.rng" type="application/xml" schematypens="http://purl.oclc.org/dsdl/schematron"?>
<mei xmlns="http://www.music-encoding.org/ns/mei" meiversion="4.0.0">
    <meiHead>
        <fileDesc>
            <titleStmt>
                <title />
            </titleStmt>
            <pubStmt />
        </fileDesc>
        <encodingDesc>
            <appInfo>
                <application isodate="2018-05-05T11:49:45" version="2.0.0-dev-686bba6-dirty">
                    <name>Verovio</name>
                    <p>Transcoded from Humdrum</p>
                </application>
            </appInfo>
        </encodingDesc>
        <workDesc>
            <work>
                <titleStmt>
                    <title />
                </titleStmt>
            </work>
        </workDesc>
    </meiHead>
    <music>
        <body>
            <mdiv xml:id="mdiv-0000001538668335">
                <score xml:id="score-0000002016557762">
                    <scoreDef xml:id="scoredef-0000000251933028" midi.bpm="400">
                        <staffGrp xml:id="staffgrp-0000001333276045">
                            <staffDef xml:id="staffdef-0000000500933001" clef.shape="C" clef.line="3" n="1" lines="5">
                                <label xml:id="label-0000000358848738" />
                            </staffDef>
                        </staffGrp>
                    </scoreDef>
                    <section xml:id="section-0000001987911118">
                        <measure xml:id="measure-L3" n="1">
                            <staff xml:id="staff-L3F1N1" n="1">
                                <layer xml:id="layer-L3F1N1" n="1">
                                    <note xml:id="note-L4F1" dur="maxima" oct="4" pname="c" accid.ges="n" />
                                    <note xml:id="note-L5F1" dur="maxima" oct="4" pname="c" stem.dir="up" accid.ges="n" />
                                    <note xml:id="note-L6F1" dur="maxima" oct="4" pname="c" stem.dir="down" accid.ges="n" />
                                </layer>
                            </staff>
                        </measure>
                        <measure xml:id="measure-L7">
                            <staff xml:id="staff-L7F1N1" n="1">
                                <layer xml:id="layer-L7F1N1" n="1">
                                    <note xml:id="note-L8F1" dur="long" oct="4" pname="c" accid.ges="n" />
                                    <note xml:id="note-L9F1" dur="long" oct="4" pname="c" stem.dir="up" accid.ges="n" />
                                    <note xml:id="note-L10F1" dur="long" oct="4" pname="c" stem.dir="down" accid.ges="n" />
                                </layer>
                            </staff>
                        </measure>
                        <measure xml:id="measure-L11" right="end">
                            <staff xml:id="staff-L11F1N1" n="1">
                                <layer xml:id="layer-L11F1N1" n="1">
                                    <note xml:id="note-L12F1" dur="2" oct="4" pname="c" accid.ges="n" />
                                    <note xml:id="note-L13F1" dur="2" oct="4" pname="c" stem.dir="up" accid.ges="n" />
                                    <note xml:id="note-L14F1" dur="2" oct="4" pname="c" stem.dir="down" accid.ges="n" />
                                </layer>
                            </staff>
                        </measure>
                    </section>
                </score>
            </mdiv>
        </body>
    </music>
</mei>
```

**Comment by rettinghaus** [comment]
This doesn't affect longs and maximas at all, because they're drawn in a different function.

**Comment by craigsapp** [comment]
Hmmm, that fix did not work: I still see stems attached to semibreves.  These should all be without stems:

screen shot 2018-05-05 at 4 57 22 pm

Test data:

```xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-model href="http://music-encoding.org/schema/4.0.0/mei-all.rng" type="application/xml" schematypens="http://relaxng.org/ns/structure/1.0"?>
<?xml-model href="http://music-encoding.org/schema/4.0.0/mei-all.rng" type="application/xml" schematypens="http://purl.oclc.org/dsdl/schematron"?>
<mei xmlns="http://www.music-encoding.org/ns/mei" meiversion="4.0.0">
    <meiHead>
        <fileDesc>
            <titleStmt>
                <title />
            </titleStmt>
            <pubStmt />
        </fileDesc>
        <encodingDesc>
            <appInfo>
                <application isodate="2018-05-05T16:57:02" version="2.0.0-dev-686bba6-dirty">
                    <name>Verovio</name>
                    <p>Transcoded from Humdrum</p>
                </application>
            </appInfo>
        </encodingDesc>
        <workDesc>
            <work>
                <titleStmt>
                    <title />
                </titleStmt>
            </work>
        </workDesc>
    </meiHead>
    <music>
        <body>
            <mdiv xml:id="mdiv-0000000336468157">
                <score xml:id="score-0000000695872148">
                    <scoreDef xml:id="scoredef-0000000296453771" midi.bpm="400">
                        <staffGrp xml:id="staffgrp-0000000124990101">
                            <staffDef xml:id="staffdef-0000000383012351" clef.shape="C" clef.line="3" n="1" notationtype="mensural" lines="5">
                                <label xml:id="label-0000000294226926" />
                            </staffDef>
                        </staffGrp>
                    </scoreDef>
                    <section xml:id="section-0000000327249874">
                        <measure xml:id="measure-L1" right="invis" n="0">
                            <staff xml:id="staff-0000001004220336" n="1">
                                <layer xml:id="layer-L1F1N1" n="1">
                                    <note xml:id="note-L3F1" dur="semibrevis" oct="4" pname="e" stem.dir="up" accid.ges="n" />
                                    <note xml:id="note-L4F1" dur="semibrevis" oct="4" pname="d" stem.dir="down" accid.ges="n" />
                                    <note xml:id="note-L5F1" dur="semibrevis" oct="4" pname="c" accid.ges="n" />
                                    <note xml:id="note-L6F1" dur="semibrevis" oct="4" pname="e" stem.dir="down" accid.ges="n" />
                                    <note xml:id="note-L7F1" dur="semibrevis" oct="4" pname="d" stem.dir="up" accid.ges="n" />
                                    <note xml:id="note-L8F1" dur="semibrevis" oct="4" pname="c" accid.ges="n" />
                                </layer>
                            </staff>
                        </measure>
                    </section>
                </score>
            </mdiv>
        </body>
    </music>
</mei>
```

**Comment by rettinghaus** [comment]
As I've written: Add `stem.visible="false"` 
Simply removing the stem by default will affect black mensural notation.

**Pull request merged**
