### PR TITLE
Small correction of note position calculation

### PR DESCRIPTION
**Pull request by lpugin**

### CODE REVIEW

**Comment by rettinghaus** [comment]
Was the change in slur-013 expected?

**Comment by lpugin** [comment]
No, well-spotted. I will fix it.

**Comment by lpugin** [comment]
image


Somehow relates to https://github.com/rism-ch/verovio/issues/920

**Comment by lpugin** [comment]
Fixed here (with a few other improvements) https://github.com/rism-ch/verovio/pull/1990#issuecomment-767439651

**Pull request merged**
