### PR TITLE
adding att.visibility to barLine

### PR DESCRIPTION
**Pull request by rettinghaus**

### CODE REVIEW

**Comment by craigsapp** [comment]
Looks great (or doesn't look great, in this case):

screen shot 2018-05-07 at 8 57 51 am

The second barline is invisible:

```xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-model href="http://music-encoding.org/schema/4.0.0/mei-all.rng" type="application/xml" schematypens="http://relaxng.org/ns/structure/1.0"?>
<?xml-model href="http://music-encoding.org/schema/4.0.0/mei-all.rng" type="application/xml" schematypens="http://purl.oclc.org/dsdl/schematron"?>
<mei xmlns="http://www.music-encoding.org/ns/mei" meiversion="4.0.0">
    <meiHead>
        <fileDesc>
            <titleStmt>
                <title />
            </titleStmt>
            <pubStmt />
        </fileDesc>
        <encodingDesc>
            <appInfo>
                <application isodate="2018-05-07T08:50:47" version="2.0.0-dev-81110a0">
                    <name>Verovio</name>
                    <p>Transcoded from Humdrum</p>
                </application>
            </appInfo>
        </encodingDesc>
        <workDesc>
            <work>
                <titleStmt>
                    <title />
                </titleStmt>
            </work>
        </workDesc>
    </meiHead>
    <music>
        <body>
            <mdiv xml:id="mdiv-0000001827838261">
                <score xml:id="score-0000000724082292">
                    <scoreDef xml:id="scoredef-0000001639055190" midi.bpm="400">
                        <staffGrp xml:id="staffgrp-0000001042681310">
                            <staffDef xml:id="staffdef-0000000264815307" clef.shape="C" clef.line="1" mensur.sign="C" mensur.slash="1" n="1" notationtype="mensural.white" lines="5">
                                <label xml:id="label-0000001148571917" />
                            </staffDef>
                        </staffGrp>
                    </scoreDef>
                    <section xml:id="section-0000002008737742">
                            <staff xml:id="staff-L6F1N1" n="1">
                                <layer xml:id="layer-L6F1N1" n="1">
                                    <note xml:id="note-L7F1" dur="semibrevis" oct="4" pname="c" accid.ges="n" />
                                    <barLine/>
                                    <note xml:id="note-L9F1" dur="semiminima" oct="3" pname="b" accid.ges="n" />
                                    <note xml:id="note-L9F1" dur="semiminima" oct="4" pname="c" accid.ges="n" />
                                    <note xml:id="note-L9F1" dur="semiminima" oct="4" pname="d" accid.ges="n" />
                                    <note xml:id="note-L9F1" dur="semiminima" oct="4" pname="e" accid.ges="n" />
                                    <barLine visible="false" />
                                    <note xml:id="note-L11F1" dur="semiminima" oct="4" pname="f" accid.ges="n" />
                                    <note xml:id="note-L11F1" dur="semiminima" oct="4" pname="g" accid.ges="n" />
                                    <note xml:id="note-L11F1" dur="minima" oct="4" pname="f" accid.ges="n" />
                                    <barLine/>
                                </layer>
                            </staff>
                    </section>
                </score>
            </mdiv>
        </body>
    </music>
</mei>
```

Ideally there would be no horizontal space given to the invisible barline.  Is that currently possible (with an attribute, or verovio styling option)?

**Comment by rettinghaus** [comment]
It's the same behaviour as with notes. So you would preferably use it for linebreaks only.

**Comment by craigsapp** [comment]
I need to typeset it to see the linebreaks, but I need the linebreaks to typeset it...

**Comment by rettinghaus** [comment]
Perhaps just avoid them between semiminimas?

**Comment by craigsapp** [comment]
That should be good for most cases.

**Pull request merged**
