### PR TITLE
Updated staff spacing calculation behaviour

### LINKED ISSUE #1693: spacingStaff option not working
The `spacingStaff` and `spacingSystem` option defaults and behaviors have changed recently.  It would be useful to post issues about these sorts of changes, describing the what and why of the changes.

The default for `spacingStaff` has changed from 8 to 12, with a range of 0-24 changed to 0-36.

The default for `spacingSystem` has changed from 3 to 12 with a range of 0-12 change to 0-48.

Why are the option ranges for `spacingStaff` and `spacingSystem` different?  Obviously because the original ranges were not identical, but the new system treats the spacings as equivalent, so it is better to make the ranges for each option the same.

In addition, see issue #1295 for suggested changes in ranges from 0 to 100.

---------------

Previously the `spacingStaff` value was placed below every staff, and `spacingStaff` was placed below every system.  This means that the previous behavior was that the true spacing between each system was `spacingStaff` + `spacingSystem`.

The new system does not add `spacingStaff` below the bottom staff of the system, so the new `spacingSystem` is what was previously `spacingStaff` + `spacingSystem`.   This of course makes sense and is easier to understand that the previous system.

| Option | Old meaning | New meaning |
| ------- | ------------ | -------------- |
| `spacingStaff` |    Place this amount of space below every staff.      | Place this amount of space between every staff within a system.           |
| `spacingSystem` |  Place this amount of space below every system.  Total space between systems includes `spacingStaff`.          |  Place this amount of space below every system.            |

------------

However, there is some sort of regression in the `spacingStaff` option as it is not working at all.   This also indicates that changes in the code were not tested for regressions, but it would be preferrable to do so at the time of a pull request.  This would be facilitated with example renderings before and after code changes affecting an option or rendering behavior being worked on, and such examples should be provided with pull requests.

With the test file at the bottom of this post, here are some examples:

The default spacings of `spacingStaff` = 12 and `spacingSystem` = 12 is working:

Screen Shot 2020-09-19 at 10 43 10 PM

However, setting `spacingStaff` to its maximum does not change anything in the example:

Screen Shot 2020-09-19 at 10 42 55 PM

Setting `spacingStaff` = 0, the minimum value also does nothing:

Screen Shot 2020-09-19 at 10 44 13 PM

Compare this to `spacingSystem` which can be changed:

Setting `spacingSystem` = 48 (maximum value):

Screen Shot 2020-09-19 at 10 45 04 PM

Setting `spacingSystem` = 0 (minimum value):

Screen Shot 2020-09-19 at 10 46 11 PM

This spacing is a bit odd and behaves differently from the previous minimum spacing, but it is a synthetic example so the difference is not important.

----------------------

Here is the test HTML file for the above examples:

```html
<html>
<head>
<title>Spacing test</title>
</head>
<body>

<div style="color:blue; font-size:2rem;" id="parameters"></div>
<div id="example"></div>

<script>
var vrvToolkit;
var Module = {
	onRuntimeInitialized: function() {
		vrvToolkit = new verovio.toolkit();
		prepareExample("example");
	}
};
</script>

<script src="https://verovio-script.humdrum.org/scripts/verovio-toolkit-wasm.js"></script>

<script>

var vrvOptions = {
	scale: 40,
	header: "none",
	pageHeight: 6000,
	adjustPageHeight: 1,
	pageWidth: 2100,
	spacingStaff: 12,
	spacingSystem: 12
}

function prepareExample(targetid) {
	var delement = document.querySelector("#humdrum-data");
	var data = delement.textContent;
	var svg = vrvToolkit.renderData(data, vrvOptions);
	var element = document.querySelector("#" + targetid);
	element.innerHTML = svg;
	var pelement = document.querySelector("#parameters");
	var output = "";
	var staff = vrvOptions.spacingStaff;
	staff = typeof staff === 'undefined' ? 12 : staff;
	var system = vrvOptions.spacingSystem;
	system = typeof system === 'undefined' ? 12 : system;
	output += "spacingStaff: " + staff + ", ";
	output += "spacingSystem: " + system;
	pelement.innerHTML = output;
}

</script>

<script type="text/x-humdrum" id="humdrum-data">**kern	**kern	**kern
*staff2	*staff1	*staff1
*clefF4	*clefG2	*clefG2
*k[]	*k[]	*k[]
*M4/4	*M4/4	*M4/4
*a:	*a:	*a:
*MM72	*MM72	*MM72
=1	=1	=1
4r	1r	1r
4e	.	.
4c	.	.
4f	.	.
=2	=2	=2
4G#	1r	1r
4r	.	.
8r	.	.
8d	.	.
8BL	.	.
8eJ	.	.
=3	=3	=3
8cL	4r	1r
8AJ	.	.
8F#L	4a	.
8d#J	.	.
8EL	4g	.
32e	.	.
32dn	.	.
32c	.	.
32BJ	.	.
8AL	4cc	.
32c	.	.
32B	.	.
32A	.	.
32GJ	.	.
=4	=4	=4
32F#L	4d#	1r
32G	.	.
[16A	.	.
32A]	.	.
32G	.	.
32F#	.	.
32EJ	.	.
32D#L	4r	.
32E	.	.
[16F#	.	.
32F#]	.	.
32E	.	.
32D#	.	.
32C#J	.	.
8.BBL	8r	.
.	8a	.
32C#	.	.
32D#J	.	.
8.D#TL	8f#L	.
.	8bJ	.
32C#	.	.
32D#J	.	.
=5	=5	=5
8EL	8gL	1r
32r	8eJ	.
32E	.	.
32Fn	.	.
32GJ	.	.
8AL	8c#L	.
32r	8aJ	.
32G	.	.
32F	.	.
32EJ	.	.
8DL	8fnL	.
32r	8dJ	.
32D	.	.
32E	.	.
32FJ	.	.
8GL	8BL	.
32r	8gJ	.
32F	.	.
32E	.	.
32DJ	.	.
=6	=6	=6
*	*strophe	*
*	*^	*
*	*S/sic	*S/ossia	*
8.CL	8e	8eL	4r
.	4axx	8cxxJ	.
16DJ	.	.	.
16EL	.	8Bxx	4ee
32F	.	.	.
32E	.	.	.
*	*v	*v	*
*	*Xstrophe	*
16D	8g#	.
16EJ	.	.
4F	8AL	4cc
.	32a	.
.	32gn	.
.	32f	.
.	32eJ	.
4r	8dL	4ff
.	32f	.
.	32e	.
.	32d	.
.	32cJ	.
=7	=7	=7
8r	32BL	4g#
.	32c	.
.	[16d	.
8F	32d]	.
.	32c	.
.	32B	.
.	32AJ	.
8BBL	32G#L	4r
.	32A	.
.	[16B	.
8DJ	32B]	.
.	32A	.
.	32G#	.
.	32F#J	.
8GG#L	8.EL	8r
8BBJ	.	8dd
.	32F#	.
.	32G#J	.
4E	8.G#TL	8bL
.	.	8eeJ
.	32F#	.
.	32G#J	.
=8	=8	=8
8AA	8AL	8ccL
8r	32r	8aJ
.	32A	.
.	32B	.
.	32cJ	.
8r	8dL	8f#L
8F#	32r	8ddJ
.	32c	.
.	32B	.
.	32AJ	.
8G	8GL	8bL
8r	32r	8gJ
.	32G	.
.	32A	.
.	32BJ	.
8r	8cL	8eL
8E	32r	8ccJ
.	32B-	.
.	32A	.
.	32GJ	.
=9	=9	=9
8FL	16FL	8aL
.	8f	.
8GJ	.	8bJ
.	[16fJ	.
8AL	32f]L	[4cc
.	32e	.
.	32f	.
.	32g	.
8GJ	32a	.
.	32g	.
.	32f	.
.	32eJ	.
8FL	[4d	32cc]L
.	.	32cc
.	.	32dd
.	.	32ee
8DJ	.	32ff
.	.	32ee
.	.	32dd
.	.	32ccJ
8GL	32d]L	4b
.	32d	.
.	32e	.
.	32f	.
8FJ	32g	.
.	32f	.
.	32e	.
.	32dJ	.
=	=	=
*-	*-	*-
</script>

</body>
</html>
```

### PR DESCRIPTION
**Pull request by rettinghaus**
- Added support of ScoreDef spacing attributes
- When `--spacing-bracket-group` or `--spacing-brace-group` is not set fallback to `--spacing-staff`
or ScoreDef spacings.

closes #1693

### CODE REVIEW

**Comment by alexgnt** [comment]
Hi @lpugin, could you please have a look at this PR.

**Comment by craigsapp** [comment]
> fallback to `--spacing-staff` or ScoreDef spacings.

What does this mean?  In other words, what do `--spacing-bracket-group` or `--spacing-brace-group` mean?

Do they describe the spacing between staves inside of a group, or do they describe the spacing after the last staff in a group?

I think the following case has been discussed: https://imslp.simssa.ca/files/imglnks/usimg/c/ca/IMSLP51963-PMLP10434-Beethoven_Werke_Breitkopf_Serie_12_No_97_Op_30_No_1.pdf

But how do `--spacing-bracket-group` or `--spacing-brace-group` apply to this case:

Screen Shot 2020-09-28 at 3 12 06 AM

where there is not brace or bracket between the two groups (violin on small staff, and piano on grand staff).

Would `--spacing-brace-group` be used to control the spacing of the staves on the grand staff?   And then `--spacing-staff` for the separation between the violin and piano parts?

And how should the spaing options deal with this score:

https://imslp.simssa.ca/files/imglnks/usimg/1/16/IMSLP283159-PMLP10136-FSchubert_Piano_Trio,_D.929_Schultze-Biesantz.pdf

Screen Shot 2020-09-28 at 3 19 00 AM

which could be interpreted as having three separate spacings: one for the piano grand staff, one for the separation between the small staves and the big staves, and one for the separation between the small staves.

Also, consideration should be given to how staff/group/system spacings interact with the `--justify-vertically` option.

**Comment by rettinghaus** [comment]
@craigsapp `--spacing-staff` option is to set/override the `spacing-staff` attribute on `scoreDef`, which 
> Specifies the minimum amount of space between adjacent staves in the same system; measured from the bottom line of the staff above to the top line of the staff below.

`--spacing-bracket-group` and `--spacing-brace-group` overrides these settings and apply to the minimal space between staves _within_ the corresponding `staffGrp`. 

If you want to set fixed absolute distances you can do it with the `spacing` attribute on each `staffDef`.

**Comment by lpugin** [comment]
@craigsapp it seems that `--spacing-staff` is now back to normal.

```xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-model href="https://music-encoding.org/schema/4.0.0/mei-all.rng" type="application/xml" schematypens="http://relaxng.org/ns/structure/1.0"?>
<?xml-model href="https://music-encoding.org/schema/4.0.0/mei-all.rng" type="application/xml" schematypens="http://purl.oclc.org/dsdl/schematron"?>
<mei xmlns="http://www.music-encoding.org/ns/mei" meiversion="4.0.0">
   <meiHead>
      <fileDesc>
         <titleStmt>
            <title>an example</title>
         </titleStmt>
         <pubStmt />
      </fileDesc>
   </meiHead>
   <music>
      <body>
         <mdiv n="1">
            <score>
               <scoreDef key.mode="major" key.pname="c" key.sig="0" meter.count="4" meter.unit="4">
                  <staffGrp symbol="brace" bar.thru="true">
                     <staffDef n="1" lines="5" clef.shape="G" clef.line="2" />
                     <staffDef n="2" lines="5" clef.shape="F" clef.line="4" />
                  </staffGrp>
               </scoreDef>
               <section>
                  <measure n="1">
                     <staff n="1">
                        <layer n="1">
                           <note dur="1" oct="5" pname="c" />
                        </layer>
                     </staff>
                     <staff n="2">
                        <layer n="1">
                           <note dur="1" oct="3" pname="c" />
                        </layer>
                     </staff>
                  </measure>
               </section>
            </score>
         </mdiv>
      </body>
   </music>
</mei>
```

with option `--spacing-staff 20`

2.7.2
image

Current develop (13a71d97e37c677c8cc6137168aea8c951f8beca)
image

This PR
image

**Comment by rettinghaus** [comment]
Controlling spacing with proposed changes:

### Default rendering:
spacingStaffNone

### options `spacingStaff: 24`
spacingStaff24

### options `spacingStaff: 24, spacingBrace: 12`
spacingStaff24spacingBrace12

### options `spacingStaff: 24, spacingBrace: 12, spacingBracket: 16`
spacingStaff24spacingBrace12spacingBracket16

**Comment by craigsapp** [comment]
Looks great!

**Pull request merged**
