### PR TITLE
Update codemeta

### PR DESCRIPTION
**Pull request by rettinghaus**
This adds all latest contributers to codemeta with minor fixes.
@lpugin You should at least keep the version number updated.

### CODE REVIEW

**Comment by lpugin** [comment]
Please make distinct PR for what was not merged

**Comment by rettinghaus** [comment]
We have this in Craig's code a million times, also e.g. in `iodarms.cpp` and `svgdevicecontext.cpp`

**Comment by lpugin** [comment]
Craig should change it ;-)

**Comment by lpugin** [comment]
FYI: it used to be invalid in ANSI C89. I kept the habit

**Pull request closed without merging**
