### PR TITLE
engraving statement 

### PR DESCRIPTION
**Pull request by rettinghaus**
This adds an `<desc>` to the SVG containing "Engraved by Verovio" + version. 
Also it removes the overflow attribute from the root element as it is useless: 
https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/overflow

### CODE REVIEW

**Comment by lpugin** [comment]
There was a reason to have the "overflow" attribute added and if I remember correctly this was a browser compatibility issue. So it would be best to leave it since I do not think it creates problems

**Comment by kepper** [comment]
I think the reason was a rule in Twitter Bootstrap, which caused several elements to be rendered only in half. Of course this only helps people using Bootstrap, but like you said, as long as it doesn't hurt anyone, it probably avoids more problems than a friendly note hidden somewhere on the website…

**Comment by craigsapp** [comment]
> I think the reason was a rule in Twitter Bootstrap, which caused several elements to be rendered only in half.

Yes, that is the problem.  Firefox needs overflow set to "inherit" to display SVG properly, but bootstrap sets it to "hidden". Here is the original issue dealing with it: #138.

To fix so that firefox and boostrap get along, this needs to be added to the CSS file for a website:

```css
svg:not(:root) {
  overflow: inherit; 
}
```

Other browsers don't care if it is "inherit" or "hidden".

**Comment by rettinghaus** [comment]
Has anyone cared to look through the link I provided? 

> If the overflow attribute has a value other than hidden or scroll, the property has no effect.

Firefox doesn't care if there's a `overflow="inherit"`or not on the root node. It is also set on every `symbol` node. And there it has to be to solve the "glyphs are rendered only half" issue.

**Comment by lpugin** [comment]
Adding the overflow attribute was not related to the Bootstrap / Firefox issue. I tested the SVG rendering with as many browsers as possible and also with SVG applications (e.g., Inkskape). There is often some differences so we cannot rely only on the Firefox specs. We would need to test is again if we change this. So I do not see a reason to remove it unless it creates some problems. Does it?

**Comment by craigsapp** [comment]
The problem with Firefox+Boostrap is independent of `@overflow` being included/excluded on the SVG root node, so it does not seem to be important to have `@overflow` on the svg root (also true in Chrome).  Firefox does not like Bootstrap setting `svg@overflow` to "hidden".  Below are test that demonstrate that.

Ideally a symbol should be configured with the `@viewbox` so that the symbol does not get clipped when overflow is set to hidden.  I played around with the viewbox of a symbol just now and had problems doing anything useful (there is also `@viewport` which might work for symbols), since I am thinking in terms of PostScript bounding boxes.  If the bounding boxes (viewports, viewboxes or whatever) are set properly, I would expect that the state of `@overflow` being either visible or hidden would not affect the image, since there would be no clipping if it were set to hidden.  The current viewboxes (or whatever) seem to be 1/2 of the symbol heights, and therefore if `@overflow="hidden"` is used, the top halves of the symbols are clipped.


-----------------


Here are some test with CSS and the overflow attribute in SVG data on a webpage in Firefox:

screen shot 2017-03-25 at 12 43 30 am

HTML:

```xml
<html>
<head>
<title> Overlay Test 1</title>
</head>
<body>

<h2> Test 1: Current SVG image with overflow="visible" </h2>


<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<svg width="2100px" height="2970px" version="1.1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" overflow="visible">
	<defs>
		<symbol id="E050" viewBox="0 0 1000 1000" overflow="inherit">
			<path transform="scale(1,-1)" d="M441 -245c-23 -4 -48 -6 -76 -6c-59 0 -102 7 -130 20c-88 42 -150 93 -187 154c-26 44 -43 103 -48 176c-4 60 11 123 44 189c29 57 65 106 110 148s96 85 153 127c-3 16 -8 46 -13 92c-4 43 -5 73 -5 89c0 117 16 172 69 257c34 54 64 82 89 82c21 0 43 -30 69 -92 s39 -115 41 -159c2 -120 -19 -173 -67 -256c-13 -20 -63 -90 -98 -118c-13 -9 -25 -19 -37 -29l31 -181c8 1 18 2 28 2c58 0 102 -12 133 -35c59 -43 92 -104 98 -184c11 -135 -80 -229 -180 -270c8 -57 17 -110 25 -162c5 -31 6 -58 6 -80c0 -30 -5 -53 -14 -70 c-35 -64 -88 -99 -158 -103c-42 -3 -83 6 -124 26c-50 24 -77 59 -80 105c-2 34 5 63 20 87c18 28 45 42 79 44c51 4 99 -40 103 -87c4 -56 -30 -94 -105 -115c17 -24 51 -36 102 -36c62 0 116 43 140 85c9 16 13 41 13 74c0 20 -1 42 -5 67c-8 53 -18 106 -26 159zM461 939 c-95 0 -135 -175 -135 -286c0 -24 2 -48 5 -71c50 39 92 82 127 128c43 57 63 106 60 148c-4 54 -23 82 -57 81zM406 119l54 -326c80 27 116 88 109 184c-7 99 -62 146 -163 142zM382 117c-74 -2 -132 -50 -128 -127c2 -46 43 -99 75 -115c-3 -2 -7 -5 -10 -10 c-70 33 -116 88 -123 172c-5 73 42 135 88 170c23 17 49 29 78 36l-29 170c-21 -13 -52 -37 -92 -73c-50 -44 -86 -84 -109 -119c-49 -75 -71 -140 -67 -195c5 -68 35 -127 93 -176s125 -73 203 -73c25 0 50 3 75 9c-19 111 -36 221 -54 331z" />
		</symbol>
		<symbol id="E084" viewBox="0 0 1000 1000" overflow="inherit">
			<path transform="scale(1,-1)" d="M0 -78c84 97 114 180 134 329h170c-13 -32 -82 -132 -99 -151l-84 -97c-33 -36 -59 -63 -80 -81h162v102l127 123v-225h57v-39h-57v-34c0 -43 19 -65 57 -65v-34h-244v36c48 0 60 26 60 70v27h-203v39z" />
		</symbol>
		<symbol id="E0A2" viewBox="0 0 1000 1000" overflow="inherit">
			<path transform="scale(1,-1)" d="M198 133c102 0 207 -45 207 -133c0 -92 -98 -133 -207 -133c-101 0 -198 46 -198 133c0 88 93 133 198 133zM293 -21c0 14 -3 29 -8 44c-7 20 -18 38 -33 54c-20 21 -43 31 -68 31l-20 -2c-15 -5 -27 -14 -36 -28c-4 -9 -6 -17 -8 -24s-3 -16 -3 -27c0 -15 3 -34 9 -57 s18 -41 34 -55c15 -15 36 -23 62 -23c4 0 10 1 18 2c19 5 32 15 40 30s13 34 13 55z" />
		</symbol>
	</defs>
	<style type="text/css">g.page-margin{font-family:Times;} g.tempo{font-weight:bold;} g.dir, g.dynam {font-style:italic;}</style>
	<svg id="definition-scale" viewBox="0 0 21000 29700">
		<g class="page-margin" transform="translate(500, 500)">
			<g class="system" id="system-0000002014322717">
				<g class="section boundaryStart" id="section-0000001150090766" />
				<g class="measure" id="measure-L3">
					<g class="staff" id="staff-L3F1N1">
						<path d="M0 1445 L3100 1445" stroke="#000000" stroke-width="20" />
						<path d="M0 1625 L3100 1625" stroke="#000000" stroke-width="20" />
						<path d="M0 1805 L3100 1805" stroke="#000000" stroke-width="20" />
						<path d="M0 1985 L3100 1985" stroke="#000000" stroke-width="20" />
						<path d="M0 2165 L3100 2165" stroke="#000000" stroke-width="20" />
						<g class="clef" id="clef-0000001882896541">
							<use xlink:href="#E050" x="90" y="1985" height="720px" width="720px" />
						</g>
						<g class="meterSig" id="msig-0000001121455884">
							<use xlink:href="#E084" x="735" y="1625" height="720px" width="720px" />
							<use xlink:href="#E084" x="735" y="1985" height="720px" width="720px" />
						</g>
						<g class="layer" id="layer-L3F1N1">
							<g class="note qon-0 qoff-4 b40-162 qon-0 qoff-4 b40-162" id="note-L4F1">
								<path d="M1293 2345 L1617 2345" stroke="#000000" stroke-width="20" />
								<use xlink:href="#E0A2" x="1305" y="2345" height="720px" width="720px" />
							</g>
						</g>
					</g>
					<g class="barLineAttr" id="bline-0000001902328747">
						<path d="M2935 1445 L2935 2165" stroke="#000000" stroke-width="30" />
						<path d="M3055 1445 L3055 2165" stroke="#000000" stroke-width="90" />
					</g>
				</g>
				<g class="boundaryEnd section-0000001150090766" id="bdend0000001166472858" />
			</g>
		</g>
	</svg>
</svg>




</body>
```

screen shot 2017-03-25 at 12 44 44 am

```xml
<html>
<head>
<title> Overlay Test 2</title>
</head>
<body>

<h2> Test 2: Current SVG image with overflow="visible" but CSS setting overflow="hidden" </h2>


<style>
svg {
	overflow: hidden;
}
</style>

<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<svg width="2100px" height="2970px" version="1.1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" overflow="visible">
	<defs>
		<symbol id="E050" viewBox="0 0 1000 1000" overflow="inherit">
			<path transform="scale(1,-1)" d="M441 -245c-23 -4 -48 -6 -76 -6c-59 0 -102 7 -130 20c-88 42 -150 93 -187 154c-26 44 -43 103 -48 176c-4 60 11 123 44 189c29 57 65 106 110 148s96 85 153 127c-3 16 -8 46 -13 92c-4 43 -5 73 -5 89c0 117 16 172 69 257c34 54 64 82 89 82c21 0 43 -30 69 -92 s39 -115 41 -159c2 -120 -19 -173 -67 -256c-13 -20 -63 -90 -98 -118c-13 -9 -25 -19 -37 -29l31 -181c8 1 18 2 28 2c58 0 102 -12 133 -35c59 -43 92 -104 98 -184c11 -135 -80 -229 -180 -270c8 -57 17 -110 25 -162c5 -31 6 -58 6 -80c0 -30 -5 -53 -14 -70 c-35 -64 -88 -99 -158 -103c-42 -3 -83 6 -124 26c-50 24 -77 59 -80 105c-2 34 5 63 20 87c18 28 45 42 79 44c51 4 99 -40 103 -87c4 -56 -30 -94 -105 -115c17 -24 51 -36 102 -36c62 0 116 43 140 85c9 16 13 41 13 74c0 20 -1 42 -5 67c-8 53 -18 106 -26 159zM461 939 c-95 0 -135 -175 -135 -286c0 -24 2 -48 5 -71c50 39 92 82 127 128c43 57 63 106 60 148c-4 54 -23 82 -57 81zM406 119l54 -326c80 27 116 88 109 184c-7 99 -62 146 -163 142zM382 117c-74 -2 -132 -50 -128 -127c2 -46 43 -99 75 -115c-3 -2 -7 -5 -10 -10 c-70 33 -116 88 -123 172c-5 73 42 135 88 170c23 17 49 29 78 36l-29 170c-21 -13 -52 -37 -92 -73c-50 -44 -86 -84 -109 -119c-49 -75 -71 -140 -67 -195c5 -68 35 -127 93 -176s125 -73 203 -73c25 0 50 3 75 9c-19 111 -36 221 -54 331z" />
		</symbol>
		<symbol id="E084" viewBox="0 0 1000 1000" overflow="inherit">
			<path transform="scale(1,-1)" d="M0 -78c84 97 114 180 134 329h170c-13 -32 -82 -132 -99 -151l-84 -97c-33 -36 -59 -63 -80 -81h162v102l127 123v-225h57v-39h-57v-34c0 -43 19 -65 57 -65v-34h-244v36c48 0 60 26 60 70v27h-203v39z" />
		</symbol>
		<symbol id="E0A2" viewBox="0 0 1000 1000" overflow="inherit">
			<path transform="scale(1,-1)" d="M198 133c102 0 207 -45 207 -133c0 -92 -98 -133 -207 -133c-101 0 -198 46 -198 133c0 88 93 133 198 133zM293 -21c0 14 -3 29 -8 44c-7 20 -18 38 -33 54c-20 21 -43 31 -68 31l-20 -2c-15 -5 -27 -14 -36 -28c-4 -9 -6 -17 -8 -24s-3 -16 -3 -27c0 -15 3 -34 9 -57 s18 -41 34 -55c15 -15 36 -23 62 -23c4 0 10 1 18 2c19 5 32 15 40 30s13 34 13 55z" />
		</symbol>
	</defs>
	<style type="text/css">g.page-margin{font-family:Times;} g.tempo{font-weight:bold;} g.dir, g.dynam {font-style:italic;}</style>
	<svg id="definition-scale" viewBox="0 0 21000 29700">
		<g class="page-margin" transform="translate(500, 500)">
			<g class="system" id="system-0000002014322717">
				<g class="section boundaryStart" id="section-0000001150090766" />
				<g class="measure" id="measure-L3">
					<g class="staff" id="staff-L3F1N1">
						<path d="M0 1445 L3100 1445" stroke="#000000" stroke-width="20" />
						<path d="M0 1625 L3100 1625" stroke="#000000" stroke-width="20" />
						<path d="M0 1805 L3100 1805" stroke="#000000" stroke-width="20" />
						<path d="M0 1985 L3100 1985" stroke="#000000" stroke-width="20" />
						<path d="M0 2165 L3100 2165" stroke="#000000" stroke-width="20" />
						<g class="clef" id="clef-0000001882896541">
							<use xlink:href="#E050" x="90" y="1985" height="720px" width="720px" />
						</g>
						<g class="meterSig" id="msig-0000001121455884">
							<use xlink:href="#E084" x="735" y="1625" height="720px" width="720px" />
							<use xlink:href="#E084" x="735" y="1985" height="720px" width="720px" />
						</g>
						<g class="layer" id="layer-L3F1N1">
							<g class="note qon-0 qoff-4 b40-162 qon-0 qoff-4 b40-162" id="note-L4F1">
								<path d="M1293 2345 L1617 2345" stroke="#000000" stroke-width="20" />
								<use xlink:href="#E0A2" x="1305" y="2345" height="720px" width="720px" />
							</g>
						</g>
					</g>
					<g class="barLineAttr" id="bline-0000001902328747">
						<path d="M2935 1445 L2935 2165" stroke="#000000" stroke-width="30" />
						<path d="M3055 1445 L3055 2165" stroke="#000000" stroke-width="90" />
					</g>
				</g>
				<g class="boundaryEnd section-0000001150090766" id="bdend0000001166472858" />
			</g>
		</g>
	</svg>
</svg>




</body>
```
screen shot 2017-03-25 at 12 47 03 am

```xml
<html>
<head>
<title> Overlay Test 3</title>
</head>
<body>

<h2> Test 3: remove overflow="visible" from svg root </h2>


<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<svg width="2100px" height="2970px" version="1.1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink">
	<defs>
		<symbol id="E050" viewBox="0 0 1000 1000" overflow="inherit">
			<path transform="scale(1,-1)" d="M441 -245c-23 -4 -48 -6 -76 -6c-59 0 -102 7 -130 20c-88 42 -150 93 -187 154c-26 44 -43 103 -48 176c-4 60 11 123 44 189c29 57 65 106 110 148s96 85 153 127c-3 16 -8 46 -13 92c-4 43 -5 73 -5 89c0 117 16 172 69 257c34 54 64 82 89 82c21 0 43 -30 69 -92 s39 -115 41 -159c2 -120 -19 -173 -67 -256c-13 -20 -63 -90 -98 -118c-13 -9 -25 -19 -37 -29l31 -181c8 1 18 2 28 2c58 0 102 -12 133 -35c59 -43 92 -104 98 -184c11 -135 -80 -229 -180 -270c8 -57 17 -110 25 -162c5 -31 6 -58 6 -80c0 -30 -5 -53 -14 -70 c-35 -64 -88 -99 -158 -103c-42 -3 -83 6 -124 26c-50 24 -77 59 -80 105c-2 34 5 63 20 87c18 28 45 42 79 44c51 4 99 -40 103 -87c4 -56 -30 -94 -105 -115c17 -24 51 -36 102 -36c62 0 116 43 140 85c9 16 13 41 13 74c0 20 -1 42 -5 67c-8 53 -18 106 -26 159zM461 939 c-95 0 -135 -175 -135 -286c0 -24 2 -48 5 -71c50 39 92 82 127 128c43 57 63 106 60 148c-4 54 -23 82 -57 81zM406 119l54 -326c80 27 116 88 109 184c-7 99 -62 146 -163 142zM382 117c-74 -2 -132 -50 -128 -127c2 -46 43 -99 75 -115c-3 -2 -7 -5 -10 -10 c-70 33 -116 88 -123 172c-5 73 42 135 88 170c23 17 49 29 78 36l-29 170c-21 -13 -52 -37 -92 -73c-50 -44 -86 -84 -109 -119c-49 -75 -71 -140 -67 -195c5 -68 35 -127 93 -176s125 -73 203 -73c25 0 50 3 75 9c-19 111 -36 221 -54 331z" />
		</symbol>
		<symbol id="E084" viewBox="0 0 1000 1000" overflow="inherit">
			<path transform="scale(1,-1)" d="M0 -78c84 97 114 180 134 329h170c-13 -32 -82 -132 -99 -151l-84 -97c-33 -36 -59 -63 -80 -81h162v102l127 123v-225h57v-39h-57v-34c0 -43 19 -65 57 -65v-34h-244v36c48 0 60 26 60 70v27h-203v39z" />
		</symbol>
		<symbol id="E0A2" viewBox="0 0 1000 1000" overflow="inherit">
			<path transform="scale(1,-1)" d="M198 133c102 0 207 -45 207 -133c0 -92 -98 -133 -207 -133c-101 0 -198 46 -198 133c0 88 93 133 198 133zM293 -21c0 14 -3 29 -8 44c-7 20 -18 38 -33 54c-20 21 -43 31 -68 31l-20 -2c-15 -5 -27 -14 -36 -28c-4 -9 -6 -17 -8 -24s-3 -16 -3 -27c0 -15 3 -34 9 -57 s18 -41 34 -55c15 -15 36 -23 62 -23c4 0 10 1 18 2c19 5 32 15 40 30s13 34 13 55z" />
		</symbol>
	</defs>
	<style type="text/css">g.page-margin{font-family:Times;} g.tempo{font-weight:bold;} g.dir, g.dynam {font-style:italic;}</style>
	<svg id="definition-scale" viewBox="0 0 21000 29700">
		<g class="page-margin" transform="translate(500, 500)">
			<g class="system" id="system-0000002014322717">
				<g class="section boundaryStart" id="section-0000001150090766" />
				<g class="measure" id="measure-L3">
					<g class="staff" id="staff-L3F1N1">
						<path d="M0 1445 L3100 1445" stroke="#000000" stroke-width="20" />
						<path d="M0 1625 L3100 1625" stroke="#000000" stroke-width="20" />
						<path d="M0 1805 L3100 1805" stroke="#000000" stroke-width="20" />
						<path d="M0 1985 L3100 1985" stroke="#000000" stroke-width="20" />
						<path d="M0 2165 L3100 2165" stroke="#000000" stroke-width="20" />
						<g class="clef" id="clef-0000001882896541">
							<use xlink:href="#E050" x="90" y="1985" height="720px" width="720px" />
						</g>
						<g class="meterSig" id="msig-0000001121455884">
							<use xlink:href="#E084" x="735" y="1625" height="720px" width="720px" />
							<use xlink:href="#E084" x="735" y="1985" height="720px" width="720px" />
						</g>
						<g class="layer" id="layer-L3F1N1">
							<g class="note qon-0 qoff-4 b40-162 qon-0 qoff-4 b40-162" id="note-L4F1">
								<path d="M1293 2345 L1617 2345" stroke="#000000" stroke-width="20" />
								<use xlink:href="#E0A2" x="1305" y="2345" height="720px" width="720px" />
							</g>
						</g>
					</g>
					<g class="barLineAttr" id="bline-0000001902328747">
						<path d="M2935 1445 L2935 2165" stroke="#000000" stroke-width="30" />
						<path d="M3055 1445 L3055 2165" stroke="#000000" stroke-width="90" />
					</g>
				</g>
				<g class="boundaryEnd section-0000001150090766" id="bdend0000001166472858" />
			</g>
		</g>
	</svg>
</svg>




</body>

```

screen shot 2017-03-25 at 12 48 19 am

```xml
<html>
<head>
<title> Overlay Test 4</title>
</head>
<body>

<h2> Test 4: remove overflow="visible" from svg root, but add CSS overflow="hidden" </h2>


<style>
svg {
	overflow: hidden;
}
</style>

<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<svg width="2100px" height="2970px" version="1.1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink">
	<defs>
		<symbol id="E050" viewBox="0 0 1000 1000" overflow="inherit">
			<path transform="scale(1,-1)" d="M441 -245c-23 -4 -48 -6 -76 -6c-59 0 -102 7 -130 20c-88 42 -150 93 -187 154c-26 44 -43 103 -48 176c-4 60 11 123 44 189c29 57 65 106 110 148s96 85 153 127c-3 16 -8 46 -13 92c-4 43 -5 73 -5 89c0 117 16 172 69 257c34 54 64 82 89 82c21 0 43 -30 69 -92 s39 -115 41 -159c2 -120 -19 -173 -67 -256c-13 -20 -63 -90 -98 -118c-13 -9 -25 -19 -37 -29l31 -181c8 1 18 2 28 2c58 0 102 -12 133 -35c59 -43 92 -104 98 -184c11 -135 -80 -229 -180 -270c8 -57 17 -110 25 -162c5 -31 6 -58 6 -80c0 -30 -5 -53 -14 -70 c-35 -64 -88 -99 -158 -103c-42 -3 -83 6 -124 26c-50 24 -77 59 -80 105c-2 34 5 63 20 87c18 28 45 42 79 44c51 4 99 -40 103 -87c4 -56 -30 -94 -105 -115c17 -24 51 -36 102 -36c62 0 116 43 140 85c9 16 13 41 13 74c0 20 -1 42 -5 67c-8 53 -18 106 -26 159zM461 939 c-95 0 -135 -175 -135 -286c0 -24 2 -48 5 -71c50 39 92 82 127 128c43 57 63 106 60 148c-4 54 -23 82 -57 81zM406 119l54 -326c80 27 116 88 109 184c-7 99 -62 146 -163 142zM382 117c-74 -2 -132 -50 -128 -127c2 -46 43 -99 75 -115c-3 -2 -7 -5 -10 -10 c-70 33 -116 88 -123 172c-5 73 42 135 88 170c23 17 49 29 78 36l-29 170c-21 -13 -52 -37 -92 -73c-50 -44 -86 -84 -109 -119c-49 -75 -71 -140 -67 -195c5 -68 35 -127 93 -176s125 -73 203 -73c25 0 50 3 75 9c-19 111 -36 221 -54 331z" />
		</symbol>
		<symbol id="E084" viewBox="0 0 1000 1000" overflow="inherit">
			<path transform="scale(1,-1)" d="M0 -78c84 97 114 180 134 329h170c-13 -32 -82 -132 -99 -151l-84 -97c-33 -36 -59 -63 -80 -81h162v102l127 123v-225h57v-39h-57v-34c0 -43 19 -65 57 -65v-34h-244v36c48 0 60 26 60 70v27h-203v39z" />
		</symbol>
		<symbol id="E0A2" viewBox="0 0 1000 1000" overflow="inherit">
			<path transform="scale(1,-1)" d="M198 133c102 0 207 -45 207 -133c0 -92 -98 -133 -207 -133c-101 0 -198 46 -198 133c0 88 93 133 198 133zM293 -21c0 14 -3 29 -8 44c-7 20 -18 38 -33 54c-20 21 -43 31 -68 31l-20 -2c-15 -5 -27 -14 -36 -28c-4 -9 -6 -17 -8 -24s-3 -16 -3 -27c0 -15 3 -34 9 -57 s18 -41 34 -55c15 -15 36 -23 62 -23c4 0 10 1 18 2c19 5 32 15 40 30s13 34 13 55z" />
		</symbol>
	</defs>
	<style type="text/css">g.page-margin{font-family:Times;} g.tempo{font-weight:bold;} g.dir, g.dynam {font-style:italic;}</style>
	<svg id="definition-scale" viewBox="0 0 21000 29700">
		<g class="page-margin" transform="translate(500, 500)">
			<g class="system" id="system-0000002014322717">
				<g class="section boundaryStart" id="section-0000001150090766" />
				<g class="measure" id="measure-L3">
					<g class="staff" id="staff-L3F1N1">
						<path d="M0 1445 L3100 1445" stroke="#000000" stroke-width="20" />
						<path d="M0 1625 L3100 1625" stroke="#000000" stroke-width="20" />
						<path d="M0 1805 L3100 1805" stroke="#000000" stroke-width="20" />
						<path d="M0 1985 L3100 1985" stroke="#000000" stroke-width="20" />
						<path d="M0 2165 L3100 2165" stroke="#000000" stroke-width="20" />
						<g class="clef" id="clef-0000001882896541">
							<use xlink:href="#E050" x="90" y="1985" height="720px" width="720px" />
						</g>
						<g class="meterSig" id="msig-0000001121455884">
							<use xlink:href="#E084" x="735" y="1625" height="720px" width="720px" />
							<use xlink:href="#E084" x="735" y="1985" height="720px" width="720px" />
						</g>
						<g class="layer" id="layer-L3F1N1">
							<g class="note qon-0 qoff-4 b40-162 qon-0 qoff-4 b40-162" id="note-L4F1">
								<path d="M1293 2345 L1617 2345" stroke="#000000" stroke-width="20" />
								<use xlink:href="#E0A2" x="1305" y="2345" height="720px" width="720px" />
							</g>
						</g>
					</g>
					<g class="barLineAttr" id="bline-0000001902328747">
						<path d="M2935 1445 L2935 2165" stroke="#000000" stroke-width="30" />
						<path d="M3055 1445 L3055 2165" stroke="#000000" stroke-width="90" />
					</g>
				</g>
				<g class="boundaryEnd section-0000001150090766" id="bdend0000001166472858" />
			</g>
		</g>
	</svg>
</svg>




</body>
```

**Comment by lpugin** [comment]
The browsers with which it was tested are Chrome, Firefox, Edge, Opera, Safari, Android browser, Maxthon, Sleipnir. Import was tested with Inkscape and Gimp. It would be good to have tested again before we remove it.

**Comment by rettinghaus** [comment]
I tested it with many browsers and it worked, but I indeed found that it doesn't work correctly with the Eye of GNOME Image Viewer and GIMP, so I put it back.

**Comment by lpugin** [comment]
Thanks

**Pull request merged**
