### PR TITLE
validated and additional examples

### PR DESCRIPTION
**Pull request by rettinghaus**
* fixed validation errors for included feature examples 
* added some new feature examples 
* adding some `@alt` to comply better with valid HTML
* added a bigger icon for modern (Apple) browsers

### CODE REVIEW

**Comment by lpugin** [comment]
OK, I merged it but for next time please make sure you do not make a pull-request with that many file changes (574) because it makes it too difficult to understand what was changes. Also, do not add any file in _site.

**Comment by lpugin** [comment]
One more comments: the files in `./_includes/features` are generated with the `./examples/features/subtrees.sh` script to be run from there. It extracts subtrees with elements having the `@label="feature-example"`.

**Comment by rettinghaus** [comment]
Understood. I'll keep that in mind.
But I still don't understand how to split commits in different pull
requests. Do I have to make different branches?

**Comment by lpugin** [comment]
I think the main problem came that you pull and merged in between (especially the doxygen update), but I am not sure what is the best way to proceed.

**Comment by rettinghaus** [comment]
@lpugin sorry again for causing trouble. 
I noticed that the coloring example is missing in the menu from the features page. 
(Although it *is* available: http://www.verovio.org/features.xhtml?id=coloring )

**Comment by musicEnfanthen** [comment]
Looking at the last [commit](https://github.com/rism-ch/verovio/pull/334/commits/afe18b375a2e86d5c1d1c4796a695596b166502e), I guess you probably added the line
> `<a id="link-coloring" class="list-group-item" href="/features.xhtml?id=coloring">Coloring</a>`

manually to `_sites/features.xhtml`.

As far as I understand these `_sites/*` files are generated automatically, you wouldn't insert any code here manually.  Instead you better add the declaration of the new file in `features.xhtml` (you can find it on the root level of `gh-pages` branch). There you can include 

> ` - id: "coloring"` [corresponding to the name of the included features/*.html file, eg. coloring.html]
> `name: "Colors"` [or whatever the submenu header is]

at the top of the file between line 9 & 10 ( `menu: shared` and `id: tempi-directives`). The file should then be included "automagically".

Don't forget to get your local `gh-pages` branch in sync not only with your fork `gh-pages`, but also with upstream (`rism-ch:gh-pages` ), before checking out the patching branch and again before commiting the patch. [I also had some git trouble when switching between verovios `develop` and `gh-pages` branch, causing GIT to think there are a thousands new files because of the change of the whole file structur].

**Comment by lpugin** [comment]
@musicEnfanthen is right: changes made to _sites/* will be overwritten.

I personally also have the repository cloned at two places, once for develop (and related branches) and once for gh-pages (and related branches) because their content quite different and switching between them can be problematic.

**Pull request merged**
