### PR TITLE
Improve slur/tie thickness calculation

### PR DESCRIPTION
**Pull request by Monceber**
A couple of changes to address slur/tie thickness to follow proper MEI units:
1. Deprecated existing thickness options by moving them to separate category. Not sure if there's another more proper way of deprecating them, since they are not a single letter options (like -b).
2. Added two pair of new options for midpoint and endpoint thickness for slurs and ties correspondingly.
3. Adjusted calculation for curve thickness to take into account penWidth and allow drawing curves that correspond exactly to the MEI unit values.

Example picture with tie having equal mid- and endpoint thickness (values are: slurEndpoint - 0.2, slurMidpoint - 0.75, tieEndpoint - 0.25, tieMidpoint - 0.25)
image

### CODE REVIEW

**Comment by lpugin** [comment]
Looks great! Can we have a the example as a test file? The parameters needs to be included in the `<extMeta>`

**Comment by Monceber** [comment]
<details><summary>Example:</summary>

```
<mei xmlns="http://www.music-encoding.org/ns/mei" meiversion="4.0.0">
  <meiHead>
    <fileDesc>
      <titleStmt>
        <title></title>
      </titleStmt>
      <pubStmt></pubStmt>
    </fileDesc>
  </meiHead>
  <music>
    <body>
      <mdiv>
        <score>
          <scoreDef>
            <staffGrp symbol="bracket">
              <staffDef n="1" lines="5" clef.shape="G" clef.line="2"/>
            </staffGrp>
          </scoreDef>
          <section>
            <pb/>
            <measure n="0">
              <staff n="1">
                <layer n="1">
                  <note pname="e" oct="4" dur="4" xml:id="m0-s1-note4"/>
                  <note pname="d" oct="4" dur="8"/>
                  <note pname="e" oct="4" dur="8" xml:id="m0-s1-note6"/>
                </layer>
              </staff>
              <slur startid="#m0-s1-note4" endid="#m0-s1-note6" curvedir="above" color="#ff0000"/>
            </measure>
            <measure n="1">
              <staff n="1">
                <layer n="1">
                  <note pname="g" oct="4" dur="4" xml:id="m1-s1-note1"/>
                  <note pname="g" oct="4" dur="16" xml:id="m1-s1-note2"/>
                </layer>
              </staff>
              <tie startid="#m1-s1-note1" endid="#m1-s1-note2" color="#ff0000"/>
            </measure>
          </section>
        </score>
      </mdiv>
    </body>
  </music>
</mei>
```

</details>

Regarding `<extMeta>` - don't think I've encountered that part yet. Is that a humdrum code that would need to be adjusted?

**Comment by rettinghaus** [comment]
I’ll add an example to the test suite.

**Comment by lpugin** [comment]
All good. Thanks

image

**Pull request merged**
