### PR TITLE
Improve mensural notation

### LINKED ISSUE #845: All stems should be stem elements
Note longer than a full note do not have a extra stem element (`<g class="stem>`) in SVG output. This is an inconsitancy. 
On the other hand, stem elements there have an id, although this make little sense, since there's no stem element in MEI.

### PR DESCRIPTION
**Pull request by rettinghaus**
fixes #845 #848 #849 #852 
fixes color problems on breves / longas

### CODE REVIEW

**Comment by rettinghaus** [comment]
This adds full support for `@loc` and `@color` to `<mensur>` and introduces SMuFL glyphs. 
semibreves

```
<?xml version="1.0" encoding="UTF-8"?>
<mei xmlns="http://www.music-encoding.org/ns/mei" meiversion="4.0.0">
  <meiHead>
    <fileDesc>
      <titleStmt>
        <title />
      </titleStmt>
      <pubStmt />
    </fileDesc>
  </meiHead>
  <music>
    <body>
      <mdiv>
        <score>
          <scoreDef>
            <staffGrp>
              <staffDef clef.shape="C" clef.line="3" mensur.sign="C" mensur.slash="1" mensur.dot="true" proport.num="3" proport.numbase="1" n="1" notationtype="mensural.white" lines="5"/>
            </staffGrp>
          </scoreDef>
          <section>
            <staff n="1">
              <layer n="1">
                <note dur="brevis" oct="3" pname="c" />
                <barLine />
                <mensur loc="0" color="yellowgreen" tempus="3" prolatio="3" label="Tempus perfectum cum prolatione perfecta" />
                <note dur="brevis" oct="4" pname="f" />
                <mensur loc="2" color="darkgoldenrod" tempus="3" prolatio="2" label="Tempus perfectum cum prolatione imperfecta" />
                <note dur="brevis" oct="4" pname="d" />
                <mensur loc="4" color="turquoise" tempus="2" prolatio="3" label="Tempus imperfectum cum prolatione perfecta" />
                <note dur="brevis" oct="3" pname="b" />
                <mensur loc="6" color="purple" tempus="2" prolatio="2" label="Tempus imperfectum cum prolatione imperfecta" />
                <note dur="brevis" oct="3" pname="g" />
                <barLine />
                <mensur loc="1" sign="O" num="3" />
                <note dur="semiminima" oct="4" pname="f" color="darkgrey" />
                <note dur="semiminima" oct="4" pname="g" color="darkgrey" />
                <note dur="longa" oct="4" pname="f" color="brown" />
                <barLine/>
                <mensur sign="C" orient="reversed" dot="true" slash="1"/>
                <note dur="semiminima" oct="4" pname="f" />
                <note dur="semiminima" oct="4" pname="g" />
                <note dur="longa" oct="4" pname="f" color="brown" />
                <barLine/>
                <mensur/>
                <note dur="semibrevis" oct="4" pname="d" />
              </layer>
            </staff>
          </section>
        </score>
      </mdiv>
    </body>
  </music>
</mei>
```
This was made with the Bravura, as the reversed C glyph in Leipzig is not SMuFL complient: 
revc
https://www.smufl.org/version/latest/glyph/mensuralProlation7/

Question: should processing of 'visual' attributes (sign, orient, dot, slash) be completely sperated from the more meaningful ones (tempus, prolatio, etc.)?

**Comment by lpugin** [comment]
About the SMuFL compliance: I was thinking about suggesting a change in SMuFL for this because it would be much better to have the reverse cut circle to be aligned as in Leipzig. Because as it is now in order to know the position of the dot/slash you need to look that the height of the glyph, and the center is given by the removing half of that value from the right position. This will work, however, only if the sign is a circle. Alternatively, a point in the glyph could be added, which would be even better.

**Comment by rettinghaus** [comment]
Ok. You raise the issue for SMuFL, and I comment out the offset for now.

**Comment by rettinghaus** [comment]
Rendering with Leipzig:
semibreves

**Pull request merged**
