### PR TITLE
Improved tuplets

### LINKED ISSUE #99: tuplet ratios
The option to have a ratio on your tuplet isn't supported yet. Instead it just defaults to the single number

### PR DESCRIPTION
**Pull request by rettinghaus**
Adds `@color`, proper support for `@bracket.visible`, initial support for `@number.format="ratio"`
Several improvements and fixes
This fixes #99 #209 #211 #212 #257 #553

tuplets
```xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-model href="http://www.music-encoding.org/schema/3.0.0/mei-all.rng" type="application/xml" schematypens="http://relaxng.org/ns/structure/1.0"?>
<?xml-model href="http://www.music-encoding.org/schema/3.0.0/mei-all.rng" type="application/xml" schematypens="http://purl.oclc.org/dsdl/schematron"?>
<mei xmlns="http://www.music-encoding.org/ns/mei" meiversion="3.0.0">
  <meiHead>
    <fileDesc>
      <titleStmt>
        <title/>
      </titleStmt>
      <pubStmt/>
      <seriesStmt>
        <title>MEILER test files</title>
      </seriesStmt>
    </fileDesc>
  </meiHead>
  <music>
    <body>
      <mdiv>
        <score>
          <scoreDef meter.count="4" meter.unit="4">
            <staffGrp>
              <staffDef n="1" clef.line="2" clef.shape="G" lines="5"/>
            </staffGrp>
          </scoreDef>
          <section>
            <measure n="1">
              <staff n="1">
                <layer n="1">
                  <tuplet num="3" numbase="2" num.place="below">
                    <note pname="g" oct="4" dur="8"/>
                    <note pname="a" oct="4" dur="8"/>
                    <note pname="b" oct="4" dur="8" stem.dir="up"/>
                  </tuplet>
                  <tuplet num="3" numbase="2" bracket.place="above" color="blue">
                    <note pname="c" oct="5" dur="8"/>
                    <note pname="b" oct="4" dur="8"/>
                    <note pname="a" oct="4" dur="8" stem.dir="down"/>
                  </tuplet>
                  <tuplet num="3" numbase="2" num.visible="false">
                    <note pname="g" oct="4" dur="8"/>
                    <note pname="a" oct="4" dur="8"/>
                    <note pname="b" oct="4" dur="8" stem.dir="up"/>
                  </tuplet>
                  <tuplet num="3" numbase="2" bracket.visible="false">
                    <note pname="c" oct="5" dur="8"/>
                    <note pname="b" oct="4" dur="8"/>
                    <note pname="a" oct="4" dur="8" stem.dir="down"/>
                  </tuplet>
                </layer>
              </staff>
            </measure>
            <measure n="2">
              <staff n="1">
                <layer n="1">
                  <beam>
                    <tuplet num="3" numbase="2" num.place="below" bracket.visible="false">
                      <note pname="g" oct="4" dur="8"/>
                      <note pname="g" oct="4" dur="8"/>
                      <note pname="g" oct="4" dur="8"/>
                    </tuplet>
                  </beam>
                  <tuplet num="3" numbase="2" bracket.place="below" num.visible="false">
                    <beam>
                      <note pname="g" oct="4" dur="8"/>
                      <note pname="g" oct="4" dur="8"/>
                      <note pname="g" oct="4" dur="8"/>
                    </beam>
                  </tuplet>
                  <beam>
                    <tuplet num="3" numbase="2" num.place="below" bracket.visible="true">
                      <note pname="g" oct="4" dur="8"/>
                      <note pname="g" oct="4" dur="8"/>
                      <note pname="g" oct="4" dur="8"/>
                    </tuplet>
                  </beam>
                  <tuplet num="3" numbase="2" bracket.place="below" num.visible="true" num.format="ratio">
                    <beam>
                      <note pname="g" oct="4" dur="8"/>
                      <note pname="g" oct="4" dur="8"/>
                      <note pname="g" oct="4" dur="8"/>
                    </beam>
                  </tuplet>
                </layer>
              </staff>
            </measure>
          </section>
        </score>
      </mdiv>
    </body>
  </music>
</mei>
```

tuplerests
```xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-model href="http://music-encoding.org/schema/3.0.0/mei-all.rng" type="application/xml" schematypens="http://relaxng.org/ns/structure/1.0"?>
<?xml-model href="http://music-encoding.org/schema/3.0.0/mei-all.rng" type="application/xml" schematypens="http://purl.oclc.org/dsdl/schematron"?>
<mei xmlns="http://www.music-encoding.org/ns/mei" meiversion="3.0.0">
  <meiHead>
    <fileDesc>
      <titleStmt>
        <title />
      </titleStmt>
    </fileDesc>
  </meiHead>
  <music>
    <body>
      <mdiv>
        <score>
          <scoreDef>
            <staffGrp>
              <staffDef clef.shape="G" clef.line="2" meter.count="4" meter.unit="4" n="1" lines="5" />
            </staffGrp>
          </scoreDef>
          <section>
            <measure n="1">
              <staff n="1">
                <layer n="1">
                  <tuplet num="3" numbase="2" bracket.visible="true" num.format="count">
                    <rest dur="8" />
                    <rest dur="8" />
                    <rest dur="8" />
                  </tuplet>
                  <tuplet num="3" numbase="2" bracket.visible="true" num.format="count">
                    <rest dur="8" loc="0"/>
                    <rest dur="8" loc="4" />
                    <rest dur="8" loc="8" />
                  </tuplet>
                  <tuplet num="3" numbase="2" bracket.visible="true" num.format="count">
                    <rest dur="8" ploc="e" oloc="4"/>
                    <rest dur="8" ploc="b" oloc="4" />
                    <rest dur="8" ploc="f" oloc="5" />
                  </tuplet>
                  <tuplet num="3" numbase="2" bracket.visible="true" num.format="count">
                    <rest dur="8" />
                    <rest dur="8" />
                    <rest dur="8" />
                  </tuplet>
                </layer>
              </staff>
            </measure>
            <measure right="end">
              <staff n="1">
                <layer n="1">
                  <tuplet num="3" numbase="2" bracket.visible="true" num.format="count">
                    <rest dur="8" />
                    <note dur="8" oct="4" pname="d" accid.ges="n" />
                    <note dur="8" oct="4" pname="e" accid.ges="n" />
                  </tuplet>
                  <tuplet num="3" numbase="2" bracket.visible="true" num.format="count">
                    <note dur="8" oct="4" pname="c" accid.ges="n" />
                    <note dur="8" oct="4" pname="d" accid.ges="n" />
                    <rest dur="8" />
                  </tuplet>
                  <tuplet num="3" numbase="2" bracket.visible="true" num.format="count">
                    <rest dur="8" />
                    <rest dur="8" />
                    <note dur="8" oct="4" pname="e" accid.ges="n" />
                  </tuplet>
                  <tuplet num="3" numbase="2" bracket.visible="true" num.format="count">
                    <note dur="8" oct="4" pname="c" accid.ges="n" />
                    <rest dur="8" />
                    <rest dur="8" />
                  </tuplet>
                </layer>
              </staff>
            </measure>
          </section>
        </score>
      </mdiv>
    </body>
  </music>
</mei>
```
tuplestemless

### CODE REVIEW

**Comment by rettinghaus** [comment]
Now shows bracket if not only tuplet is beamed
beamedtuplets

```xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-model href="http://www.music-encoding.org/schema/3.0.0/mei-all.rng" type="application/xml" schematypens="http://relaxng.org/ns/structure/1.0"?>
<?xml-model href="http://www.music-encoding.org/schema/3.0.0/mei-all.rng" type="application/xml" schematypens="http://purl.oclc.org/dsdl/schematron"?>
<mei xmlns="http://www.music-encoding.org/ns/mei" meiversion="3.0.0">
  <meiHead>
    <fileDesc>
      <titleStmt>
        <title/>
      </titleStmt>
      <pubStmt/>
      <seriesStmt>
        <title>MEILER test files</title>
      </seriesStmt>
    </fileDesc>
  </meiHead>
  <music>
    <body>
      <mdiv>
        <score>
          <scoreDef meter.count="4" meter.unit="4">
            <staffGrp>
              <staffDef n="1" clef.line="1" clef.shape="C" lines="5"/>
            </staffGrp>
          </scoreDef>
          <section>
            <measure>
              <staff n="1">
                <layer n="1">
                  <beam>
                    <tuplet num="3" numbase="2">
                      <note pname="f" oct="4" dur="8"/>
                      <note pname="f" oct="4" dur="8"/>
                      <note pname="f" oct="4" dur="8"/>
                    </tuplet>
                  </beam>
                  <tuplet num="3" numbase="2">
                    <beam>
                      <note pname="f" oct="4" dur="8"/>
                      <note pname="f" oct="4" dur="8"/>
                      <note pname="f" oct="4" dur="8"/>
                    </beam>
                  </tuplet>
                  <beam>
                    <note pname="f" oct="4" dur="8"/>
                    <tuplet num="3" numbase="2">
                      <note pname="f" oct="4" dur="8"/>
                      <note pname="f" oct="4" dur="8"/>
                      <note pname="f" oct="4" dur="8"/>
                    </tuplet>
                    <note pname="f" oct="4" dur="8"/>
                  </beam>
                </layer>
              </staff>
            </measure>
          </section>
        </score>
      </mdiv>
    </body>
  </music>
</mei>
```

**Comment by rettinghaus** [comment]
nested duplets work now, but has to be revised when support for `@bracket.place` and `@num.place` is added. 

stackedtuplets
```xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-model href="http://www.music-encoding.org/schema/3.0.0/mei-all.rng" type="application/xml" schematypens="http://relaxng.org/ns/structure/1.0"?>
<?xml-model href="http://www.music-encoding.org/schema/3.0.0/mei-all.rng" type="application/xml" schematypens="http://purl.oclc.org/dsdl/schematron"?>
<mei xmlns="http://www.music-encoding.org/ns/mei" meiversion="3.0.0">
  <meiHead>
    <fileDesc>
      <titleStmt>
        <title/>
      </titleStmt>
      <pubStmt/>
      <seriesStmt>
        <title>MEILER test files</title>
      </seriesStmt>
    </fileDesc>
  </meiHead>
  <music>
    <body>
      <mdiv>
        <score>
          <scoreDef meter.count="4" meter.unit="4">
            <staffGrp>
              <staffDef n="1" clef.line="1" clef.shape="C" lines="5"/>
            </staffGrp>
          </scoreDef>
          <section>
            <measure>
              <staff n="1">
                <layer n="1">
                  <tuplet num="7" numbase="8">
                    <note pname="c" oct="5" dur="8"/>
                    <note pname="c" oct="4" dur="8"/>
                    <beam>
                      <tuplet num="5" numbase="4" num.format="ratio">
                        <tuplet num="3" numbase="2">
                          <note pname="e" oct="4" dur="8"/>
                          <note pname="f" oct="4" dur="8"/>
                          <note pname="g" oct="4" dur="8"/>
                        </tuplet>
                        <beam>
                          <tuplet num="3" numbase="2">
                            <note pname="b" oct="4" dur="8"/>
                            <note pname="e" oct="4" dur="8"/>
                            <note pname="b" oct="3" dur="8"/>
                          </tuplet>
                        </beam>
                        <note pname="c" oct="4" dur="8"/>
                      </tuplet>
                    </beam>
                    <note pname="a" oct="4" dur="8"/>
                  </tuplet>
                </layer>
              </staff>
            </measure>
          </section>
        </score>
      </mdiv>
    </body>
  </music>
</mei>
```

**Comment by lpugin** [comment]
Thanks. Eventually I would like to make the brackets and the figure child element of tuplet for better layout / collision calculation.

**Comment by lpugin** [comment]
How is it working in terms of duration alignment? As far as I can see nested tuplets should not align correctly. Or did you change this too?

**Comment by rettinghaus** [comment]
Basically I just touched `view_tuplet.cpp`. It's way from perfect, but nonetheless a huge improvement.

**Comment by rettinghaus** [comment]
@craigsapp Could you give this a shot and play around with it?

**Pull request merged**
