### PR TITLE
updated setup.py to compile all files in setum/hum/*.cpp

### PR DESCRIPTION
**Pull request by misingnoglic**
Change related to issues found in #603

### CODE REVIEW

**Comment by ahankinson** [comment]
Why did you merge this to master?

**Comment by craigsapp** [comment]
Oops, because I was presuming that the commit branch was develop and didn't check.  Probably easiest to also add manually to the develop branch since it will probably be useful to keep in the master and it is a small change.

**Comment by ahankinson** [comment]
I will revert these. The pull request will have to be re-submitted against `develop`.

**Comment by ahankinson** [comment]
Ah, but you've already done that. So I'll just remove it from master.

**Comment by craigsapp** [comment]
Yes that is good.  I don't want to remove from the master just in case I instead remove the master ...

**Comment by ahankinson** [comment]
Done.

**Pull request merged**
