### PR TITLE
Improve vertical justification of last page

### PR DESCRIPTION
**Pull request by Monceber**
Changed logic so that last page would be justified regardless of the additional options, if `--justify-vertically` option has been provided.
Justification for last page is based on the spacing/proportions of the previous one if there are not enough of systems in it.

### CODE REVIEW

**Comment by craigsapp** [comment]
> Justification for last page is based on the spacing/proportions of the previous one if there are not enough of systems in it.

That is great!

What happens if there is only one page of music and `--justify-vertically` is used?

**Comment by Monceber** [comment]
If that's the case, behavior remains unchanged from what it is right now - justification will be based on calculated values (since there is no previous page).

**Comment by craigsapp** [comment]
> If that's the case, behavior remains unchanged from what it is right now - justification will be based on calculated values (since there is no previous page).

OK.  But note this silly situation (which I probably reported in the issues but cannot find):

https://editor.verovio.org/?file=https://raw.githubusercontent.com/rism-ch/verovio.org/gh-pages/_tests/clef/clef-001.mei

Then select PDF download, and then view the resulting PDF:

Screen Shot 2020-09-10 at 7 56 14 AM

**Comment by Monceber** [comment]
@craigsapp 
I think this is a separate issue (and I'm not sure it's a correct one on top of that). A check can be added that justification should be skipped if first page is the last page. However, we will kill some proper use cases with this approach.
For instance, we want to have proper justification in cases when first page has more than 10 staves (approximately). And running justification for such examples is more realistic than running it for the score with one page and two staves, imo.

**Comment by lpugin** [comment]
The issue reported by @craigsapp was introduced in the refactoring of the justification. This is clearly an issue and it should be fixed. I would suggest to fix it before removing the include-last-page option.

**Comment by rettinghaus** [comment]
@lpugin but why is it working in the browser and only the PDF is looking this strange?

**Comment by lpugin** [comment]
I think is it because it has the option "justifyIncludeLastPage" set to true for the PDF.

**Comment by craigsapp** [comment]
> For instance, we want to have proper justification in cases when first page has more than 10 staves (approximately). And running justification for such examples is more realistic than running it for the score with one page and two staves, imo.

Yes, if someone wants to print short examples like this, they should not turn on the vertical justification option.  Although for non-technical users, how to do this might not be apparent, since they would be using an interface such as the MEI viewer and printing from the menu without awareness of the options (and if it is possible to change them).

Perhaps a maximum vertical staff spacing option could be useful to autodetect such cases: if staves would vertically be adjusted beyond a certain distance (such as 100 diatonic steps, or about 10 staff heights), then vertical justification for that page would be disabled (not set to the maximum).  If someone wanted to override the default maximum vertical spacing, they could set the maximum to a larger value, such as 1000 diatonic steps, which would probably be more than the page height.

Of course, such an option would be outside of the scope of this pull request.

> @lpugin but why is it working in the browser and only the PDF is looking this strange?

I suspect that vertical justification is being added only in the PDF rendering, while in the viewer it is not. (as I see @lpugin has just stated).

**Comment by Monceber** [comment]
For the time being I've made change so that we are basing such cases (when there is only one page) on the amount of the staves that are present. In case when we have only a handful of them, we won't justify to avoid situation like above (where two staves are stretched over the whole page). When there is more reasonable amount for us to justify page, then we do it.

This approach is probably is not the best out there and in the long run option for the maximum spacing as @craigsapp suggested is a way to go. However at this point it does solve this edge case. If there are objections to this approach, please let me know.

**Comment by craigsapp** [comment]
That sounds good for now, and your solution should only fail for short pages with only a few staves on the system.  This might occur in on-screen situations, but all of the current online verovio interfaces that I know of do not use vertical justification for the screen display, only for creating PDFs.

**Comment by Monceber** [comment]
@lpugin Are you ok with these changes?

**Pull request merged**
