### PR TITLE
pimped colors example

### PR DESCRIPTION
**Pull request by rettinghaus**
I improved the colors example for the features page and updated `supported-mei.yml`.

### CODE REVIEW

**Comment by pe-ro** [comment]
What exactly does "pimped colors" mean? 😀

**Comment by craigsapp** [comment]
> What exactly does "pimped colors" mean?

What are you thinking of? ;-)

https://www.pinterest.com/explore/pimped-out-cars

**Comment by pe-ro** [comment]
I get "pimped out".  But it's hard for me to understand what "color pimping" entails. Is it legal in the Mid-West?  :-)

**Comment by craigsapp** [comment]
Not after tomorrow...

**Comment by lpugin** [comment]
Let me merge and see ;-)

**Pull request merged**
