### PR TITLE
Implement support for engravingDefaults as option

### PR DESCRIPTION
**Pull request by Monceber**
Solution for the #1555 

Added an option that would work as following:
./verovio -a -r ../Data test.mei **--engraving-defaults config.json**

Existing options are retained in default configuration that is read when no option is provided. Existing options are left untouched and would override corresponding value when provided, e.g.
./verovio -a -r ../Data test.mei --engraving-defaults config.json **--stem-width 0.4**

Stem width option would be used even if there is stemThickness configuration in the config.json.

### CODE REVIEW

**Comment by lpugin** [comment]
It is good to have this new option to load SMuFL options. However, internally, it should be the other way around. That is, simply copy the JSON / SMuFL option to each Verovio option as appropriate, and not the other way around. This will be simpler and more efficient.

**Review by lpugin — CHANGES_REQUESTED** [review]
See comment

**Review by lpugin — COMMENTED** [review]
For some reasons I can still see the old changes. Maybe the simplest is to redo a fresh PR with the latest solution? The only thing I see needs to be changed is `Options::sync` to be capitalized as `Options::Sync`

**Comment by Monceber** [comment]
I'll create new PR if that the case.

**Pull request closed without merging**
