### PR TITLE
Initial support for cue notes

### PR DESCRIPTION
**Pull request by rettinghaus**
This adds support for `@size` on all supported elements. 
For now setting `@size="cue"` works so far for rests and single notes (heads). 
Beamed notes and chords are somewhat trickier as of horizontal alignement. I leave that to @lpugin 

NOTE: cued grace notes will not be possible with the current drawing methods. 

cues

```xml
<mei xmlns="http://www.music-encoding.org/ns/mei" meiversion="3.0.0">
  <meiHead>
    <fileDesc>
      <titleStmt>
        <title />
      </titleStmt>
      <pubStmt>
      </pubStmt>
    </fileDesc>
    <encodingDesc>
    </encodingDesc>
  </meiHead>
  <music>
    <body>
      <mdiv>
        <score>
          <scoreDef>
            <staffGrp>
              <staffDef clef.shape="G" clef.line="2" meter.count="3" meter.unit="4" n="1" lines="5" />
            </staffGrp>
          </scoreDef>
          <section>
            <measure n="1">
              <staff n="1">
                <layer n="1">
                  <note dots="1" dur="4" oct="4" pname="g" stem.dir="up" size="cue"/>
                  <note dur="8" oct="4" pname="f" stem.dir="up" size="cue">
                    <accid accid="s" />
                  </note>
                  <beam>
                    <note dur="8" oct="4" pname="g" stem.dir="up" size="cue" />
                    <note dur="8" oct="4" pname="b" stem.dir="up" size="cue" />
                  </beam>
                </layer>
              </staff>
            </measure>
            <measure n="2" right="end">
              <staff n="1">
                <layer n="1">
                  <chord dots="1" dur="2" stem.dir="up" size="cue">
                    <note oct="4" pname="c" />
                    <note oct="4" pname="e" size="cue" />
                    <note oct="4" pname="g" />
                    <note oct="5" pname="c" />
                  </chord>
                </layer>
              </staff>
            </measure>
          </section>
        </score>
      </mdiv>
    </body>
  </music>
</mei>
```

### CODE REVIEW

**Comment by lpugin** [comment]
I merged it in develop-alignment. Could you have a check? Thanks!

**Comment by rettinghaus** [comment]
Building develop-alignment I get some errors in `system.h` and `view_control.cpp`. 
One is this: view_control.cpp:1751:107: error: invalid conversion from ‘int’ to ‘vrv::Object*’

**Comment by lpugin** [comment]
Can you try again? I pushed some fixes

**Comment by rettinghaus** [comment]
Looks good! Only single cued notes within chords have to be connected to the stem.

**Comment by rettinghaus** [comment]
real life example: 

cue2_001

```xml
<mei xmlns="http://www.music-encoding.org/ns/mei" meiversion="3.0.0">
  <meiHead>
    <fileDesc>
      <titleStmt>
        <title />
      </titleStmt>
      <pubStmt>
      </pubStmt>
    </fileDesc>
    <encodingDesc>
    </encodingDesc>
  </meiHead>
  <music>
    <body>
      <mdiv>
        <score>
          <scoreDef>
            <staffGrp>
              <staffDef clef.shape="G" clef.line="2" key="1f" n="1" lines="5" />
            </staffGrp>
          </scoreDef>
          <section>
            <measure n="81">
              <staff n="1">
                <layer n="1">
                  <note dur="2" oct="5" pname="c" accid="s" tie="i"/>
                  <note dur="8" oct="5" pname="c" accid.ges="s" tie="t"/>
                  <chord dots="1" dur="8" stem.dir="up" >
                    <note oct="3" pname="a" />
                    <note oct="4" pname="a" size="cue" />
                  </chord>
                </layer>
              </staff>
            </measure>
            <measure n="82">
              <staff n="1">
                <layer n="1">
                  <chord dots="1" dur="2" stem.dir="up" >
                    <note oct="3" pname="a" />
                    <note oct="4" pname="a" size="cue" />
                  </chord>
                </layer>
                <rest dur="4"/>
              </staff>
            </measure>
          </section>
        </score>
      </mdiv>
    </body>
  </music>
</mei>
```

**Comment by lpugin** [comment]
Actually not straightforward to fix in a clean way. Could you make it as an issue?

**Pull request closed without merging**
