### PR TITLE
Improve automatic positioning for cross staff rests

### PR DESCRIPTION
**Pull request by Monceber**
Improvements for cross-staff rests, so that they follow defined rules for automatic placement.
image

<details><summary>Example</summary>

```
<?xml version="1.0" encoding="UTF-8"?>
<?xml-model href="https://music-encoding.org/schema/4.0.0/mei-all.rng" type="application/xml" schematypens="http://relaxng.org/ns/structure/1.0"?>
<?xml-model href="https://music-encoding.org/schema/4.0.0/mei-all.rng" type="application/xml" schematypens="http://purl.oclc.org/dsdl/schematron"?>
<mei xmlns="http://www.music-encoding.org/ns/mei" meiversion="4.0.0">
   <meiHead>
      <fileDesc>
         <titleStmt>
            <title>Cross-staff rests</title>
            <respStmt />
         </titleStmt>
         <pubStmt><availability />
         </pubStmt>
      </fileDesc>
   </meiHead>
   <music>
      <body>
         <mdiv>
            <score>
               <scoreDef>
                  <staffGrp>
                     <staffGrp symbol="brace" bar.thru="true">
                        <label>Piano</label>
                        <labelAbbr>Pno.</labelAbbr>
                        <instrDef midi.channel="0" midi.instrnum="0" midi.volume="78.00%" />
                        <staffDef n="1" lines="5" ppq="1" clef.shape="G" clef.line="2" key.sig="0" meter.count="3" meter.unit="4" />
                        <staffDef n="2" lines="5" ppq="1" clef.shape="F" clef.line="4" key.sig="0" meter.count="3" meter.unit="4" />
                     </staffGrp>
                  </staffGrp>
               </scoreDef>
               <section>
                  <pb />
		  <measure n="5">
                     <staff n="1">
                        <layer n="5">
                           <note dur="4" oct="4" pname="c" stem.dir="down" />
                           <note dur="4" oct="4" pname="d" stem.dir="down" />
                           <note dur="4" oct="4" pname="e" stem.dir="down" />
                        </layer>
                     </staff>
                     <staff n="2">
			<layer n="1">
                           <rest dur="4" staff="1" />
                           <rest dur="4" staff="1" />
                           <rest dur="4" staff="1" />
                        </layer>
                        <layer n="2">
                           <note dur="4" oct="2" pname="a" stem.dir="up" />
                           <note dur="4" oct="3" pname="c" stem.dir="up" />
                           <note dur="4" oct="3" pname="e" stem.dir="up" />
                        </layer>
                     </staff>
                  </measure>
                  <measure n="6">
                     <staff n="1">
                        <layer n="5">
                           <note dur="4" oct="4" pname="f" stem.dir="down" />
                           <note dur="4" oct="4" pname="g" stem.dir="down" />
                           <note dur="4" oct="4" pname="a" stem.dir="down" />
                        </layer>
                     </staff>
                     <staff n="2">
                        <layer n="1">
                           <rest dur="4" staff="1" />
                           <rest dur="4" staff="1" />
                           <rest dur="4" staff="1" />
                        </layer>
                        <layer n="2">
                           <note dur="4" oct="3" pname="g" stem.dir="up" />
                           <note dur="4" oct="3" pname="b" stem.dir="up" />
                           <note dur="4" oct="4" pname="d" stem.dir="up" />
                        </layer>
                     </staff>
                  </measure>
                  <measure n="7">
                     <staff n="1">
                        <layer n="5">
                           <note dur="4" oct="4" pname="b" stem.dir="down" />
                           <note dur="4" oct="5" pname="c" stem.dir="down" />
                           <note dur="4" oct="5" pname="d" stem.dir="down" />
                        </layer>
                     </staff>
                     <staff n="2">
			<layer n="1">
                           <note dur="4" oct="2" pname="a" stem.dir="up" />
                           <note dur="4" oct="3" pname="c" stem.dir="up" />
                           <note dur="4" oct="3" pname="e" stem.dir="up" />
                        </layer>
			<layer n="2">
                           <rest dur="4" staff="1" />
                           <rest dur="4" staff="1" />
                           <rest dur="4" staff="1" />
                        </layer>
                     </staff>
                  </measure>
                  <measure right="end" n="8">
                     <staff n="1">
                        <layer n="5">
                           <note dur="4" oct="5" pname="e" stem.dir="down" />
                           <note dur="4" oct="5" pname="f" stem.dir="down" />
                           <note dur="4" oct="5" pname="g" stem.dir="down" />
                        </layer>
                     </staff>
                     <staff n="2">
                        <layer n="1">
                           <note dur="4" oct="3" pname="g" stem.dir="up" />
                           <note dur="4" oct="3" pname="b" stem.dir="up" />
                           <note dur="4" oct="4" pname="d" stem.dir="up" />
                        </layer>
			<layer n="2">
                           <rest dur="4" staff="1" />
                           <rest dur="4" staff="1" />
                           <rest dur="4" staff="1" />
                        </layer>
                     </staff>
		   </measure>
               </section>
            </score>
         </mdiv>
      </body>
   </music>
</mei>

```

</details>

### CODE REVIEW

**Comment by lpugin** [comment]
Thanks! Only to double check - it also lowers the position of some rests. It this intended / OK?
Before
image
After
image

@rettinghaus could you add the example to the test-suite?

**Comment by craigsapp** [comment]
Is there a reason for `@layer="5"` when there is only layer on a staff?  Presumably it is due to the data coming from MusicXML, but I do not recall the verovio MusicXML-to-MEI converter doing that.

**Comment by Monceber** [comment]
@craigsapp That is actually a very good question. It probably got somewhere in between converting XML to MEI and manual editing of the file to get testing example. However there is a problem in the code where it actually compares layer numbers and would not work if the numbering was correct. I'll have it as separate PR shortly.

**Comment by Monceber** [comment]
@lpugin Some of the positions moved due to the change of the default offsets for the corresponding (quarter) rests. I think it's okay-ish, since it still follow the same rules for the same/other layers, just offset is decreased.

**Pull request merged**
