### PR TITLE
use prefix operator for iteration

### PR DESCRIPTION
**Pull request by rettinghaus**

### CODE REVIEW

**Comment by craigsapp** [comment]
Why?

**Comment by lpugin** [comment]
I think it is more efficient because there is not copy to be made. (I doubt it makes a noticeable difference, but there is no reason not to change this.)

**Comment by craigsapp** [comment]
OK.  If `++` is being applied to a built-in type (integer), then it will not matter since the code will be optimized by the compiler (such as by using `-O3` option).  If you define `++` for your own class, then there will be a difference that probably cannot be optimized out by the compiler.  

If you want to be efficient, then don't use XML 😛

**Comment by rettinghaus** [comment]
Indeed it is faster for non-primitive types. It doesn't make much sense for built-in types, but I switched it there, too, for consistent coding style.

**Comment by craigsapp** [comment]
Are you going to try to make me change it in the `iohumdrum.cpp` file?   At least I won't complain if you do it :-)

**Pull request merged**
