### PR TITLE
Develop trem

### LINKED ISSUE #630: stem ignores bTrem slashes
as in beams bTrem slashes should make stems longer to avoid collision of glyphs

btrem-collision

``` xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-model href="https://music-encoding.org/schema/4.0.1/mei-all.rng" type="application/xml" schematypens="http://relaxng.org/ns/structure/1.0"?>
<?xml-model href="https://music-encoding.org/schema/4.0.1/mei-all.rng" type="application/xml" schematypens="http://purl.oclc.org/dsdl/schematron"?>
<mei xmlns="http://www.music-encoding.org/ns/mei" meiversion="4.0.1">
  <meiHead>
    <fileDesc>
      <titleStmt>
        <title>Many slashes in tremolos</title>
      </titleStmt>
      <pubStmt>
        <respStmt>
          <persName role="encoder">Klaus Rettinghaus</persName>
        </respStmt>
        <date isodate="2017">2017</date>
      </pubStmt>
      <notesStmt>
        <annot>bTrem slashes should make stems longer to avoid collision of glyphs.</annot>
      </notesStmt>
    </fileDesc>
  </meiHead>
  <music>
    <body>
      <mdiv>
        <score>
          <scoreDef meter.count="3" meter.unit="4" key.sig="3f">
            <staffGrp>
              <staffDef n="1" lines="5" clef.line="2" clef.shape="G"/>
            </staffGrp>
          </scoreDef>
          <section>
            <measure>
              <staff n="1">
                <layer n="1">
                  <bTrem unitdur="256">
                    <chord dur="4" stem.dir="down" stem.mod="6slash">
                      <note oct="4" pname="f" accid="s"/>
                      <note oct="5" pname="c"/>
                    </chord>
                  </bTrem>
                  <bTrem unitdur="256">
                    <chord dur="4" stem.dir="up" stem.mod="6slash">
                      <note oct="5" pname="e"/>
                      <note oct="4" pname="e"/>
                    </chord>
                  </bTrem>
                  <bTrem unitdur="256">
                    <note oct="5" pname="e" dur="4" stem.dir="up" stem.mod="6slash"/>
                  </bTrem>
                </layer>
              </staff>
            </measure>
          </section>
        </score>
      </mdiv>
    </body>
  </music>
</mei>
```

NB: Stems with many flags should get longer, too. From the "musical perspective" the stem length is a function of the (effective) note duration and not one of the beam. 
In this example all notes have the same effective duration, so they should show equal stem lengths: 

btrem-collision

(the flagged notes look like their stems are long enough, but they are as long as on the first note)

### LINKED ISSUE #1881: Stem shortening + tremolo interaction
When stems are shortened because they are off of the staff, tremolos should be considered:

Screen Shot 2020-12-12 at 10 39 20 PM

For the first two beats the tremolo placement is correct; however for the third beam, the tremolos collide with the noteheads because the stems were shortened.  In the case of 32nd-note tremolos, the stems cannot be shortened. (16th note tremolos will probably be OK)

MEI test data:

```xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-model href="https://music-encoding.org/schema/4.0.0/mei-all.rng" type="application/xml" schematypens="http://relaxng.org/ns/structure/1.0"?>
<?xml-model href="https://music-encoding.org/schema/4.0.0/mei-all.rng" type="application/xml" schematypens="http://purl.oclc.org/dsdl/schematron"?>
<mei xmlns="http://www.music-encoding.org/ns/mei" meiversion="4.0.0">
 <meiHead>
  <fileDesc>
   <titleStmt>
    <title />
   </titleStmt>
   <pubStmt />
  </fileDesc>
  <encodingDesc>
   <appInfo>
    <application isodate="2020-12-12T22:39:29" version="3.1.0-dev-6bf947d-dirty">
     <name>Verovio</name>
     <p>Transcoded from Humdrum</p>
    </application>
   </appInfo>
  </encodingDesc>
  <workList>
   <work>
    <title />
   </work>
  </workList>
 </meiHead>
 <music>
  <body>
   <mdiv xml:id="mdiv-0000000839474275">
    <score xml:id="score-0000001728156683">
     <scoreDef xml:id="scoredef-0000000706445092">
      <staffGrp xml:id="staffgrp-0000000039804925">
       <staffDef xml:id="staffdef-0000000397992776" n="1" lines="5">
        <clef xml:id="clef-0000001350086321" shape="G" line="2" />
        <meterSig xml:id="metersig-L2F1" count="4" unit="4" />
       </staffDef>
      </staffGrp>
     </scoreDef>
     <section xml:id="section-L1F1">
      <measure xml:id="measure-L1" n="1">
       <staff xml:id="staff-0000000570081573" n="1">
        <layer xml:id="layer-L1F1N1" n="1">
         <bTrem xml:id="btrem-L5F1-L12F1" unitdur="32">
          <note xml:id="note-L5F1" dur="4" oct="5" pname="f" accid.ges="n" />
         </bTrem>
         <bTrem xml:id="btrem-L13F1-L20F1" unitdur="32">
          <note xml:id="note-L13F1" dur="4" oct="4" pname="e" accid.ges="n" />
         </bTrem>
         <bTrem xml:id="btrem-L22F1-L29F1" unitdur="32">
          <note xml:id="note-L22F1" dur="4" oct="5" pname="f" accid.ges="n" />
         </bTrem>
         <rest xml:id="rest-L31F1" dur="4" />
        </layer>
        <layer xml:id="layer-L22F2N2" n="2">
         <space xml:id="space-0000000952223096" dur="2" />
         <bTrem xml:id="btrem-L22F2-L29F2" unitdur="32">
          <note xml:id="note-L22F2" dur="4" oct="4" pname="e" accid.ges="n" />
         </bTrem>
         <space xml:id="space-0000002084322210" dur="4" />
        </layer>
       </staff>
      </measure>
     </section>
    </score>
   </mdiv>
  </body>
 </music>
</mei>
```

### PR DESCRIPTION
**Pull request by rettinghaus**
fix stem length calculation for tremolo slashes 
closes #630
closes #1881

TremSlashes

```xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-model href="https://music-encoding.org/schema/4.0.0/mei-all.rng" type="application/xml" schematypens="http://relaxng.org/ns/structure/1.0"?>
<?xml-model href="https://music-encoding.org/schema/4.0.0/mei-all.rng" type="application/xml" schematypens="http://purl.oclc.org/dsdl/schematron"?>
<mei xmlns="http://www.music-encoding.org/ns/mei" meiversion="4.0.0">
   <meiHead>
    <fileDesc>
        <titleStmt>
          <title>Stem length calculation for bowed tremolos</title>
        </titleStmt>
        <pubStmt>
          <respStmt>
            <persName>Klaus Rettinghaus</persName>
          </respStmt>
        </pubStmt>
      </fileDesc>
     </meiHead>
   <music>
      <body>
         <mdiv>
            <score>
               <scoreDef>
                  <staffGrp>
                     <staffDef n="1" lines="5">
                        <clef shape="G" line="2" />
                     </staffDef>
                  </staffGrp>
               </scoreDef>
               <section>
                  <measure right="dbl">
                     <staff n="1">
                        <layer n="1">
                           <bTrem>
                              <note dur="4" oct="4" pname="g" stem.mod="none" accid.ges="n" />
                           </bTrem>
                           <bTrem>
                              <note dur="4" oct="4" pname="g" stem.mod="1slash" accid.ges="n" />
                           </bTrem>
                           <bTrem>
                              <note dur="4" oct="4" pname="g" stem.mod="2slash" accid.ges="n" />
                           </bTrem>
                           <bTrem>
                              <note dur="4" oct="4" pname="g" stem.mod="3slash" accid.ges="n" />
                           </bTrem>
                           <bTrem>
                              <note dur="4" oct="4" pname="g" stem.mod="4slash" accid.ges="n" />
                           </bTrem>
                           <bTrem>
                              <note dur="4" oct="4" pname="g" stem.mod="5slash" accid.ges="n" />
                           </bTrem>
                           <bTrem>
                              <note dur="4" oct="4" pname="g" stem.mod="6slash" accid.ges="n" />
                           </bTrem>
                           <bTrem>
                              <note dur="4" oct="4" pname="g" stem.mod="z" accid.ges="n" />
                           </bTrem>
                        </layer>
                        <layer n="2">
                           <bTrem>
                              <note dur="4" oct="4" pname="g" stem.mod="none" accid.ges="n" />
                           </bTrem>
                           <bTrem>
                              <note dur="4" oct="4" pname="g" stem.mod="1slash" accid.ges="n" />
                           </bTrem>
                           <bTrem>
                              <note dur="4" oct="4" pname="g" stem.mod="2slash" accid.ges="n" />
                           </bTrem>
                           <bTrem>
                              <note dur="4" oct="4" pname="g" stem.mod="3slash" accid.ges="n" />
                           </bTrem>
                           <bTrem>
                              <note dur="4" oct="4" pname="g" stem.mod="4slash" accid.ges="n" />
                           </bTrem>
                           <bTrem>
                              <note dur="4" oct="4" pname="g" stem.mod="5slash" accid.ges="n" />
                           </bTrem>
                           <bTrem>
                              <note dur="4" oct="4" pname="g" stem.mod="6slash" accid.ges="n" />
                           </bTrem>
                           <bTrem>
                              <note dur="4" oct="4" pname="g" stem.mod="z" accid.ges="n" />
                           </bTrem>
                        </layer>
                     </staff>
                  </measure>
                  <measure right="dbl">
                     <staff n="1">
                        <layer n="1">
                           <bTrem>
                              <note dur="4" oct="4" pname="f" stem.mod="none" accid.ges="n" />
                           </bTrem>
                           <bTrem>
                              <note dur="4" oct="4" pname="f" stem.mod="1slash" accid.ges="n" />
                           </bTrem>
                           <bTrem>
                              <note dur="4" oct="4" pname="f" stem.mod="2slash" accid.ges="n" />
                           </bTrem>
                           <bTrem>
                              <note dur="4" oct="4" pname="f" stem.mod="3slash" accid.ges="n" />
                           </bTrem>
                           <bTrem>
                              <note dur="4" oct="4" pname="f" stem.mod="4slash" accid.ges="n" />
                           </bTrem>
                           <bTrem>
                              <note dur="4" oct="4" pname="f" stem.mod="5slash" accid.ges="n" />
                           </bTrem>
                           <bTrem>
                              <note dur="4" oct="4" pname="f" stem.mod="6slash" accid.ges="n" />
                           </bTrem>
                           <bTrem>
                              <note dur="4" oct="4" pname="f" stem.mod="z" accid.ges="n" />
                           </bTrem>
                        </layer>
                        <layer n="2">
                           <bTrem>
                              <note dur="4" oct="4" pname="f" stem.mod="none" accid.ges="n" />
                           </bTrem>
                           <bTrem>
                              <note dur="4" oct="4" pname="f" stem.mod="1slash" accid.ges="n" />
                           </bTrem>
                           <bTrem>
                              <note dur="4" oct="4" pname="f" stem.mod="2slash" accid.ges="n" />
                           </bTrem>
                           <bTrem>
                              <note dur="4" oct="4" pname="f" stem.mod="3slash" accid.ges="n" />
                           </bTrem>
                           <bTrem>
                              <note dur="4" oct="4" pname="f" stem.mod="4slash" accid.ges="n" />
                           </bTrem>
                           <bTrem>
                              <note dur="4" oct="4" pname="f" stem.mod="5slash" accid.ges="n" />
                           </bTrem>
                           <bTrem>
                              <note dur="4" oct="4" pname="f" stem.mod="6slash" accid.ges="n" />
                           </bTrem>
                           <bTrem>
                              <note dur="4" oct="4" pname="f" stem.mod="z" accid.ges="n" />
                           </bTrem>
                        </layer>
                     </staff>
                  </measure>
                  <measure right="dbl">
                     <staff n="1">
                        <layer n="1">
                           <bTrem>
                              <note dur="4" oct="4" pname="e" stem.mod="none" accid.ges="n" />
                           </bTrem>
                           <bTrem>
                              <note dur="4" oct="4" pname="e" stem.mod="1slash" accid.ges="n" />
                           </bTrem>
                           <bTrem>
                              <note dur="4" oct="4" pname="e" stem.mod="2slash" accid.ges="n" />
                           </bTrem>
                           <bTrem>
                              <note dur="4" oct="4" pname="e" stem.mod="3slash" accid.ges="n" />
                           </bTrem>
                           <bTrem>
                              <note dur="4" oct="4" pname="e" stem.mod="4slash" accid.ges="n" />
                           </bTrem>
                           <bTrem>
                              <note dur="4" oct="4" pname="e" stem.mod="5slash" accid.ges="n" />
                           </bTrem>
                           <bTrem>
                              <note dur="4" oct="4" pname="e" stem.mod="6slash" accid.ges="n" />
                           </bTrem>
                           <bTrem>
                              <note dur="4" oct="4" pname="e" stem.mod="z" accid.ges="n" />
                           </bTrem>
                        </layer>
                        <layer n="2">
                           <bTrem>
                              <note dur="4" oct="4" pname="e" stem.mod="none" accid.ges="n" />
                           </bTrem>
                           <bTrem>
                              <note dur="4" oct="4" pname="e" stem.mod="1slash" accid.ges="n" />
                           </bTrem>
                           <bTrem>
                              <note dur="4" oct="4" pname="e" stem.mod="2slash" accid.ges="n" />
                           </bTrem>
                           <bTrem>
                              <note dur="4" oct="4" pname="e" stem.mod="3slash" accid.ges="n" />
                           </bTrem>
                           <bTrem>
                              <note dur="4" oct="4" pname="e" stem.mod="4slash" accid.ges="n" />
                           </bTrem>
                           <bTrem>
                              <note dur="4" oct="4" pname="e" stem.mod="5slash" accid.ges="n" />
                           </bTrem>
                           <bTrem>
                              <note dur="4" oct="4" pname="e" stem.mod="6slash" accid.ges="n" />
                           </bTrem>
                           <bTrem>
                              <note dur="4" oct="4" pname="e" stem.mod="z" accid.ges="n" />
                           </bTrem>
                        </layer>
                     </staff>
                  </measure>
                  <measure right="dbl">
                     <staff n="1">
                        <layer n="1">
                           <bTrem>
                              <note dur="4" oct="5" pname="g" stem.mod="none" accid.ges="n" />
                           </bTrem>
                           <bTrem>
                              <note dur="4" oct="5" pname="g" stem.mod="1slash" accid.ges="n" />
                           </bTrem>
                           <bTrem>
                              <note dur="4" oct="5" pname="g" stem.mod="2slash" accid.ges="n" />
                           </bTrem>
                           <bTrem>
                              <note dur="4" oct="5" pname="g" stem.mod="3slash" accid.ges="n" />
                           </bTrem>
                           <bTrem>
                              <note dur="4" oct="5" pname="g" stem.mod="4slash" accid.ges="n" />
                           </bTrem>
                           <bTrem>
                              <note dur="4" oct="5" pname="g" stem.mod="5slash" accid.ges="n" />
                           </bTrem>
                           <bTrem>
                              <note dur="4" oct="5" pname="g" stem.mod="6slash" accid.ges="n" />
                           </bTrem>
                           <bTrem>
                              <note dur="4" oct="5" pname="g" stem.mod="z" accid.ges="n" />
                           </bTrem>
                        </layer>
                        <layer n="2">
                           <bTrem>
                              <note dur="4" oct="5" pname="g" stem.mod="none" accid.ges="n" />
                           </bTrem>
                           <bTrem>
                              <note dur="4" oct="5" pname="g" stem.mod="1slash" accid.ges="n" />
                           </bTrem>
                           <bTrem>
                              <note dur="4" oct="5" pname="g" stem.mod="2slash" accid.ges="n" />
                           </bTrem>
                           <bTrem>
                              <note dur="4" oct="5" pname="g" stem.mod="3slash" accid.ges="n" />
                           </bTrem>
                           <bTrem>
                              <note dur="4" oct="5" pname="g" stem.mod="4slash" accid.ges="n" />
                           </bTrem>
                           <bTrem>
                              <note dur="4" oct="5" pname="g" stem.mod="5slash" accid.ges="n" />
                           </bTrem>
                           <bTrem>
                              <note dur="4" oct="5" pname="g" stem.mod="6slash" accid.ges="n" />
                           </bTrem>
                           <bTrem>
                              <note dur="4" oct="5" pname="g" stem.mod="z" accid.ges="n" />
                           </bTrem>
                        </layer>
                     </staff>
                  </measure>
               </section>
            </score>
         </mdiv>
      </body>
   </music>
</mei>
```

### CODE REVIEW

**Review by lpugin — CHANGES_REQUESTED** [review]
There is a side effect on stem length. See this and other cases in the test-suite
image

**Comment by lpugin** [comment]
Thanks. Could you merge develop and redo the PR ? Then we can see if the PR comment (which I just changed) works.

**Comment by rettinghaus** [comment]
Seems to be ok now. But still a problem with the action.

**Comment by lpugin** [comment]
Yes, we need to forget the PR comment. Too bad. I fixed it.

**Pull request merged**
