### PR TITLE
Add an Overview page

### PR DESCRIPTION
**Pull request by marie-ototoi**
Images exported from keynote (source included) - quick and easy tool for that kind of schema
If this is a problem for updates I could draw them in SVG

Did not include info about installation and compilation discussed in #323

### CODE REVIEW

**Comment by craigsapp** [comment]
The diagrams all look ok.  "Command line toolkit" would better be termed "Command line interface":
http://www.catb.org/esr/writings/taouu/html/ch02s02.html

A toolkit would be used inside of a command-line interface.  Verovio is a single command (tool) in the CLI, but toolkits are collections of tools, so using the term "toolkit" for verovio in the CLI context does not quite make sense.   For the Java/Python/JavaScript it can be thought more as a toolkit since it is used as a collection of functions to mainpulate MEI data.

I am wondering how CSS is used to manipulate MIDI data :-)

**Comment by marie-ototoi** [comment]
I can leave CSS out if you think there's a risk for misunderstanding.

**Comment by craigsapp** [comment]
There won't be a chance of misunderstanding, just amusement since CSS can't be applied to MIDI data (at least I can't imagine how).

**Comment by lpugin** [comment]
Hi Marie,

It looks pretty good, thanks for this. I'll have a closer look next week. I don't think the arrow to the MIDI is a problem. It is obvious that it refers to the JavaScript and not the CSS. We actually do this with the player.

One thing that we could add is some XSLT on the server, but maybe this is going to be too much and confusing.

**Comment by craigsapp** [comment]
> One thing that we could add is some XSLT on the server, but maybe this is going to be too much and confusing.

Or XSLT processing could be done in the browser as well...

**Comment by lpugin** [comment]
Yes, there is so many ways to use Verovio... ;-)

**Comment by marie-ototoi** [comment]
Hi Laurent,
Sorry, XSLT processing got lost on the way, this was your first comment... I will add it !

**Comment by lpugin** [comment]
I cannot open the keynote file because I have an older version (6.2) ... could you save it for this version? Otherwise we should have the figures as plain svg

**Comment by marie-ototoi** [comment]
In an open world SVG makes more sense

**Pull request merged**
