### PR TITLE
Alternate stem direction based on the layer number

### PR DESCRIPTION
**Pull request by Monceber**
- changed logic of the stem direction so that it's alternated depending on the layer number (down for even-numbered layers, up - for odd)

### CODE REVIEW

**Review by rettinghaus — APPROVED** [review]

**Comment by lpugin** [comment]
Since there is not issue about this it should be illustrated. Thanks

**Comment by Monceber** [comment]
<details><summary>This example is rendered as following:</summary>
<p>

```
<?xml version="1.0" encoding="UTF-8"?>
<?xml-model href="https://music-encoding.org/schema/4.0.0/mei-all.rng" type="application/xml" schematypens="http://relaxng.org/ns/structure/1.0" ?>
<?xml-model href="https://music-encoding.org/schema/4.0.0/mei-all.rng" type="application/xml" schematypens="http://purl.oclc.org/dsdl/schematron" ?>
<mei xmlns="http://www.music-encoding.org/ns/mei" meiversion="4.0.0">
    <meiHead>
        <fileDesc>
            <titleStmt>
                <title>Multiple layers</title>
            </titleStmt>
        </fileDesc>
    </meiHead>
    <music>
        <body>
            <mdiv>
                <score>
                    <scoreDef>
                        <staffGrp>
                            <staffDef n="1" lines="5" meter.count="7" meter.unit="8" clef.shape="G" clef.line="2" />
                        </staffGrp>
                    </scoreDef>
                    <section>
                        <measure>
                            <staff n="1">
                                <layer n="1">
                                    <note dur="2" oct="5" pname="b" />
                                    <note dur="4" oct="5" pname="b" />
                                    <note dur="8" oct="5" pname="b" />
                                </layer>
                                <layer n="2">
                                    <note dur="2" oct="5" pname="f" />
                                    <note dur="4" oct="5" pname="f" />
                                    <note dur="8" oct="5" pname="f" />
                                </layer>
                                <layer n="3">
                                    <note dur="2" oct="4" pname="b" />
                                    <note dur="4" oct="4" pname="b" />
                                    <note dur="8" oct="4" pname="b" />
                                </layer>
				<layer n="4">
                                    <note dur="2" oct="4" pname="e" />
                                    <note dur="4" oct="4" pname="e" />
                                    <note dur="8" oct="4" pname="e" />
                                </layer>
                            </staff>
                        </measure>
                    </section>
                </score>
            </mdiv>
        </body>
    </music>
</mei>
```
</p>
</details>

image

**Comment by craigsapp** [comment]
How are partial layers handled by the PR?

Example:

Screen Shot 2020-09-29 at 7 18 52 AM

When there are `<spaces>` in all other layers, the remaining layer should be treated as a single layer for automatic stem direction assignment.


MEI test data:

```xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-model href="https://music-encoding.org/schema/4.0.0/mei-all.rng" type="application/xml" schematypens="http://relaxng.org/ns/structure/1.0"?>
<?xml-model href="https://music-encoding.org/schema/4.0.0/mei-all.rng" type="application/xml" schematypens="http://purl.oclc.org/dsdl/schematron"?>
<mei xmlns="http://www.music-encoding.org/ns/mei" meiversion="4.0.0">
 <meiHead>
  <fileDesc>
   <titleStmt>
    <title />
   </titleStmt>
   <pubStmt />
  </fileDesc>
  <encodingDesc>
   <appInfo>
    <application isodate="2020-09-29T07:19:00" version="3.0.0-dev-069b8f8-dirty">
     <name>Verovio</name>
     <p>Transcoded from Humdrum</p>
    </application>
   </appInfo>
  </encodingDesc>
  <workList>
   <work>
    <title />
   </work>
  </workList>
 </meiHead>
 <music>
  <body>
   <mdiv xml:id="mdiv-0000001522308956">
    <score xml:id="score-0000001144697222">
     <scoreDef xml:id="scoredef-0000001621351976">
      <staffGrp xml:id="staffgrp-0000000528524160">
       <staffDef xml:id="staffdef-0000000543724673" n="1" lines="5">
        <clef xml:id="clef-0000002060388338" shape="G" line="2" />
        <meterSig xml:id="metersig-L2F1" count="4" unit="4" />
       </staffDef>
      </staffGrp>
     </scoreDef>
     <section xml:id="section-L1F1">
      <measure xml:id="measure-L1" right="invis" n="1">
       <staff xml:id="staff-0000001244460218" n="1">
        <layer xml:id="layer-L1F1N1" n="1">
         <note xml:id="note-L4F1" dur="4" oct="5" pname="f" accid.ges="n" />
         <note xml:id="note-L6F1" dur="4" oct="5" pname="c" accid.ges="n" />
         <note xml:id="note-L8F1" dur="4" oct="5" pname="g" accid.ges="n" />
        </layer>
        <layer xml:id="layer-L6F2N2" n="2">
         <space xml:id="space-0000001968463169" dur="4" />
         <note xml:id="note-L6F2" dur="4" oct="4" pname="e" accid.ges="n" />
         <space xml:id="space-0000001541622757" dur="4" />
        </layer>
       </staff>
      </measure>
     </section>
    </score>
   </mdiv>
  </body>
 </music>
</mei>
```

**Comment by rettinghaus** [comment]
@craigsapp This behaviour hasn't changed. Just: Alternating layers will get alternating default stem directions.

**Comment by craigsapp** [comment]
> @craigsapp This behaviour hasn't changed. Just: Alternating layers will get alternating default stem directions.

OK, that is good.  Alternating automatic stem directions for each layer is great!

**Pull request merged**
