### PR TITLE
fix #1399

### LINKED ISSUE #1399: Negative effects caused by mSpace
Here is a snippet from K. 527/7. We noticed a negative behavior of `mSpace` in the latest Verovio version (2.7.0-dev-02b4f36).

capture_064_03042020_194012a

There are two problems. 

1. In the example, the `mRest` in mm. 34ff are rendered as multiRest or double whole rest which seemd to be caused by the presence of `mSpace` elements in layer 2 of the bassoon staff (later in the oboe as well).
It also creates some extra wide space:
capture_064_03042020_194012bb

2. The stem direction for bassoon 1 in mm. 34ff is now up, while we had it intentionally set in a way that the `mSpace` would not affect the stem direction. Basson 1 in layer 1 should be rendered as if there were no second layer.
Rendering was fine up to version 2.6.0 (see screenshot). 
capture_065_03042020_194524aa

Here is some code:

```
<?xml version="1.0" encoding="UTF-8"?>
<?xml-model href="https://music-encoding.org/schema/3.0.0/mei-all.rng" type="application/xml" schematypens="http://relaxng.org/ns/structure/1.0"?>
<mei meiversion="3.0.0" xmlns="http://www.music-encoding.org/ns/mei">
	<meiHead>
		<fileDesc>
			<titleStmt>
				<title>K.527/07 m.33ff</title>
				<respStmt/>
			</titleStmt>
			<pubStmt/>
		</fileDesc>
	</meiHead>
	<music>
		<body>
			<mdiv xml:id="mdiv_527007">
				<score xml:id="score_480">
					<scoreDef key.mode="major" key.pname="a" key.sig="3s" meter.count="2" meter.unit="4" n="1" xml:id="scoreDef_01">
						<staffGrp barthru="false" xml:id="staffGrp_01">
							<staffGrp barthru="true" symbol="bracket" xml:id="staffGrp_02">
								<staffDef clef.line="2" clef.shape="G" lines="5" n="1" xml:id="staffDef_P1">
									<label xml:id="label_P1">Flauto</label>
								</staffDef>
								<staffDef clef.line="2" clef.shape="G" lines="5" n="2" xml:id="staffDef_P2">
									<label xml:id="label_P2">Oboe I, II</label>
									<layerDef n="1" xml:id="layerDef_Ob1"/>
									<layerDef n="2" xml:id="layerDef_Ob2"/>
								</staffDef>
								<staffDef clef.line="4" clef.shape="F" lines="5" n="3" xml:id="staffDef_P3">
									<label xml:id="label_P3">Fagotto I, II</label>
									<layerDef n="1" xml:id="layerDef_Fag1"/>
									<layerDef n="2" xml:id="layerDef_Fag2"/>
								</staffDef>
							</staffGrp>
							<staffGrp symbol="bracket" xml:id="staffGrp_03">
								<staffDef clef.line="2" clef.shape="G" key.sig="0" lines="5" n="4" trans.diat="-2" trans.semi="-3" xml:id="staffDef_P4">
									<label xml:id="label_P4">Corno I, II <lb/> in La/A </label>
									<layerDef n="1" xml:id="layerDef_Cor1"/>
									<layerDef n="2" xml:id="layerDef_Cor2"/>
								</staffDef>
							</staffGrp>
						</staffGrp>
					</scoreDef>
					<section xml:id="section_5277">
						<measure n="33" xml:id="m33_k527_007">
							<staff n="1" xml:id="staff_19068">
								<layer n="1" xml:id="layer_19074">
									<note dur="8" oct="5" pname="e" tstamp="1" xml:id="note_19080"/>
									<note dur="4" oct="5" pname="e" tstamp="1.5" xml:id="note_19086"/>
									<note dur="8" oct="5" pname="e" tstamp="2.5" xml:id="note_19092"/>
								</layer>
							</staff>
							<staff n="2" xml:id="staff_19104">
								<layer n="1" xml:id="layer_19110">
									<rest dur="8" tstamp="1" xml:id="rest_19116"/>
									<beam xml:id="beam_19122">
										<note dur="8" oct="5" pname="d" tstamp="1.5" xml:id="note_19128"/>
										<note accid.ges="s" dur="8" oct="5" pname="c" tstamp="2" xml:id="note_19134"/>
										<note dur="8" oct="4" pname="b" tstamp="2.5" xml:id="note_19140"/>
									</beam>
								</layer>
								<layer n="2" xml:id="layer_19152">
									<rest sameas="#rest_19116" tstamp="1" xml:id="rest_19158"/>
									<beam xml:id="beam_19164">
										<note dur="8" oct="4" pname="b" tstamp="1.5" xml:id="note_19170"/>
										<note dur="8" oct="4" pname="a" tstamp="2" xml:id="note_19176"/>
										<note accid.ges="s" dur="8" oct="4" pname="g" tstamp="2.5" xml:id="note_19182"/>
									</beam>
								</layer>
							</staff>
							<staff n="3" xml:id="staff_19197">
								<layer n="1" xml:id="layer_19203">
									<beam xml:id="beam_19209">
										<note dur="8" oct="3" pname="e" tstamp="1" xml:id="note_19215"/>
										<note dur="8" oct="3" pname="b" tstamp="1.5" xml:id="note_19221"/>
										<note accid.ges="s" dur="8" oct="4" pname="c" tstamp="2" xml:id="note_19227"/>
										<note dur="8" oct="4" pname="d" tstamp="2.5" xml:id="note_19233"/>
									</beam>
								</layer>
								<layer n="2" xml:id="layer_19245">
									<rest dur="8" tstamp="1" xml:id="rest_19251"/>
									<beam xml:id="beam_19257">
										<note accid.ges="s" dur="8" oct="3" pname="g" tstamp="1.5" xml:id="note_19263"/>
										<note dur="8" oct="3" pname="a" tstamp="2" xml:id="note_19269"/>
										<note dur="8" oct="3" pname="b" tstamp="2.5" xml:id="note_19275"/>
									</beam>
								</layer>
							</staff>
							<staff n="4" xml:id="staff_19290">
								<layer n="1" xml:id="layer_19296">
									<note dur="2" oct="4" pname="g" tstamp="1" xml:id="note_19302"/>
								</layer>
								<layer n="2" xml:id="layer_19311">
									<note dur="2" oct="3" pname="g" stem.sameas="#note_19302" tstamp="1" xml:id="note_19317"/>
								</layer>
							</staff>
							<dynam staff="1" startid="#note_19080" vgrp="1" xml:id="dynam_19554">p</dynam>
							<dynam staff="1" tstamp="1.3" vgrp="1" xml:id="dynam_19566">cresc.</dynam>
							<dynam layer="1 2" staff="2" startid="#note_19128" vgrp="1" xml:id="dynam_19581">p</dynam>
							<dynam layer="1 2" staff="2" tstamp="1.8" vgrp="1" xml:id="dynam_19593">cresc.</dynam>
							<dynam layer="1 2" staff="3" startid="#note_19221" vgrp="1" xml:id="dynam_19602">p</dynam>
							<dynam layer="1 2" staff="3" tstamp="1.8" vgrp="1" xml:id="dynam_19611">cresc.</dynam>
							<dynam layer="1 2" staff="4" startid="#note_19302" vgrp="1" xml:id="dynam_19620">p</dynam>
							<dynam layer="1 2" staff="4" tstamp="1.3" vgrp="1" xml:id="dynam_19632">cresc.</dynam>
							<slur endid="#note_19776" staff="2" startid="#note_19128" xml:id="slur_19647"/>
							<slur endid="#note_19803" staff="2" startid="#note_19170" xml:id="slur_19656"/>
							<slur endid="#note_19839" staff="3" startid="#note_19221" xml:id="slur_19668"/>
							<slur endid="#note_19866" staff="3" startid="#note_19263" xml:id="slur_19677"/>
							<tie endid="#note_19902" staff="4" startid="#note_19302" xml:id="tie_19683"/>
						</measure>
						<measure n="34" xml:id="m34_k527_007">
							<staff n="1" xml:id="staff_19704">
								<layer n="1" xml:id="layer_19710">
									<beam xml:id="beam_19716">
										<note dots="1" dur="8" oct="5" pname="a" tstamp="1" xml:id="note_19722"/>
										<note dur="16" oct="5" pname="b" tstamp="1.75" xml:id="note_19728"/>
									</beam>
									<beam xml:id="beam_19737">
										<note accid.ges="s" dur="8" oct="6" pname="c" tstamp="2" xml:id="note_19743"/>
										<note dur="8" oct="5" pname="a" tstamp="2.5" xml:id="note_19749"/>
									</beam>
								</layer>
							</staff>
							<staff n="2" xml:id="staff_19764">
								<layer n="1" xml:id="layer_19770">
									<note accid.ges="s" dur="8" oct="5" pname="c" tstamp="1" xml:id="note_19776"/>
									<rest dur="8" layer="1 2" tstamp="1.5" xml:id="rest_19782"/>
									<rest dur="4" layer="1 2" tstamp="2" xml:id="rest_19788"/>
								</layer>
								<layer n="2" xml:id="layer_19797">
									<note dur="8" oct="4" pname="a" tstamp="1" xml:id="note_19803"/>
									<rest sameas="#rest_19782" tstamp="1.5" xml:id="rest_19809"/>
									<rest sameas="#rest_19788" tstamp="2" xml:id="rest_19815"/>
								</layer>
							</staff>
							<staff n="3" xml:id="staff_19827">
								<layer n="1" xml:id="layer_19833">
									<note accid.ges="s" dur="8" oct="4" pname="c" tstamp="1" xml:id="note_19839"/>
									<rest dur="8" layer="1 2" tstamp="1.5" xml:id="rest_19845"/>
									<rest dur="4" layer="1 2" tstamp="2" xml:id="rest_19851"/>
								</layer>
								<layer n="2" xml:id="layer_19860">
									<note dur="8" oct="3" pname="a" tstamp="1" xml:id="note_19866"/>
									<rest sameas="#rest_19845" tstamp="1.5" xml:id="rest_19872"/>
									<rest sameas="#rest_19851" tstamp="2" xml:id="rest_19878"/>
								</layer>
							</staff>
							<staff n="4" xml:id="staff_19890">
								<layer n="1" xml:id="layer_19896">
									<note dur="8" oct="4" pname="g" tstamp="1" xml:id="note_19902"/>
									<rest dur="8" tstamp="1.5" xml:id="rest_19908"/>
									<rest dur="4" tstamp="2" xml:id="rest_19914"/>
								</layer>
								<layer n="2" xml:id="layer_19923">
									<note dur="8" oct="4" pname="c" tstamp="1" xml:id="note_19929"/>
									<rest sameas="#rest_19908" tstamp="1.5" xml:id="rest_19935"/>
									<rest sameas="#rest_19914" tstamp="2" xml:id="rest_19941"/>
								</layer>
							</staff>
							<dynam staff="1" startid="#note_19722" vgrp="1" xml:id="dynam_20301">p</dynam>
							<dynam layer="1 2" staff="2" startid="#note_19776" vgrp="1" xml:id="dynam_20313">p</dynam>
							<dynam layer="1 2" staff="3" startid="#note_19839" vgrp="1" xml:id="dynam_20322">p</dynam>
							<dynam layer="1 2" staff="4" startid="#note_19902" vgrp="1" xml:id="dynam_20331">p</dynam>
							<slur endid="#note_19749" staff="1" startid="#note_19722" xml:id="slur_20340"/>
						</measure>
						<measure n="35" xml:id="m35_k527_007">
							<staff n="1" xml:id="staff_20355">
								<layer n="1" xml:id="layer_20361">
									<note dur="4" oct="6" pname="d" tstamp="1" xml:id="note_20367"/>
									<rest dur="4" tstamp="2" xml:id="rest_20373"/>
								</layer>
							</staff>
							<staff n="2" xml:id="staff_20385">
								<layer n="1" xml:id="layer_20391">
									<mRest tstamp="1" xml:id="mRest_20397"/>
								</layer>
								<layer n="2" sameas="#layer_20391" xml:id="layer_20391b"/>
							</staff>
							<staff n="3" xml:id="staff_20409">
								<layer n="1" xml:id="layer_20415">
									<rest dur="4" tstamp="1" xml:id="rest_20421"/>
									<rest dur="8" tstamp="2" xml:id="rest_20427"/>
									<note dur="8" oct="4" pname="d" tstamp="2.5" xml:id="note_20433"/>
								</layer>
								<layer n="2" xml:id="layer_20415b">
									<mSpace tstamp="1" xml:id="mspace_20435"/>
								</layer>
							</staff>
							<staff n="4" xml:id="staff_20445">
								<layer n="1" xml:id="layer_20451">
									<mRest tstamp="1" xml:id="mRest_20457"/>
								</layer>
								<layer n="2" sameas="#layer_20451" xml:id="layer_20451b"/>
							</staff>
							<dir layer="1" place="above" staff="3" tstamp="2" xml:id="dir_20706">
								<rend fontstyle="normal" xml:id="rend_20706a">1 <rend rend="sup" xml:id="rend_20706">mo</rend>
								</rend>
							</dir>
						</measure>
						<measure n="36" xml:id="m36_k527_007">
							<staff n="1" xml:id="staff_20727">
								<layer n="1" xml:id="layer_20733">
									<mRest tstamp="1" xml:id="mRest_20739"/>
								</layer>
							</staff>
							<staff n="2" xml:id="staff_20751">
								<layer n="1" xml:id="layer_20757">
									<mRest tstamp="1" xml:id="mRest_20763"/>
								</layer>
								<layer n="2" sameas="#layer_20757" xml:id="layer_20757b"/>
							</staff>
							<staff n="3" xml:id="staff_20775">
								<layer n="1" xml:id="layer_20781">
									<note dur="16" grace="unknown" oct="4" pname="d" stem.dir="up" xml:id="note_20787"/>
									<beam xml:id="beam_20793">
										<note accid.ges="s" dots="1" dur="8" oct="3" pname="g" tstamp="1" xml:id="note_20799"/>
										<note accid.ges="s" dur="16" oct="3" pname="g" tstamp="1.75" xml:id="note_20805"/>
									</beam>
									<beam xml:id="beam_20814">
										<note accid.ges="s" dur="8" oct="3" pname="g" tstamp="2" xml:id="note_20820"/>
										<note dur="16" oct="3" pname="a" tstamp="2.5" xml:id="note_20826"/>
										<note dur="16" oct="3" pname="b" tstamp="2.75" xml:id="note_20832"/>
									</beam>
								</layer>
								<layer n="2" xml:id="layer_20781b">
									<mSpace tstamp="1" xml:id="mspace_20834"/>
								</layer>
							</staff>
							<staff n="4" xml:id="staff_20847">
								<layer n="1" xml:id="layer_20853">
									<mRest tstamp="1" xml:id="mRest_20859"/>
								</layer>
								<layer n="2" sameas="#layer_20853" xml:id="layer_20853b"/>
							</staff>
							<slur curvedir="below" endid="#note_20799" staff="3" startid="#note_20787" xml:id="slur_21162"/>
							<slur endid="#note_20832" staff="3" startid="#note_20820" xml:id="slur_21171"/>
						</measure>
						<measure n="37" xml:id="m37_k527_007">
							<staff n="1" xml:id="staff_21216">
								<layer n="1" xml:id="layer_21222">
									<beam xml:id="beam_21228">
										<note dots="1" dur="8" oct="5" pname="a" tstamp="1" xml:id="note_21234"/>
										<note dur="16" oct="5" pname="b" tstamp="1.75" xml:id="note_21240"/>
									</beam>
									<beam xml:id="beam_21249">
										<note accid.ges="s" dur="8" oct="6" pname="c" tstamp="2" xml:id="note_21255"/>
										<note dur="8" oct="5" pname="a" tstamp="2.5" xml:id="note_21261"/>
									</beam>
								</layer>
							</staff>
							<staff n="2" xml:id="staff_21276">
								<layer n="1" xml:id="layer_21282">
									<beam xml:id="beam_21288">
										<note dots="1" dur="8" oct="4" pname="a" tstamp="1" xml:id="note_21294"/>
										<note dur="16" oct="4" pname="b" tstamp="1.75" xml:id="note_21300"/>
									</beam>
									<beam xml:id="beam_21309">
										<note accid.ges="s" dur="8" oct="5" pname="c" tstamp="2" xml:id="note_21315"/>
										<note dur="8" oct="4" pname="a" tstamp="2.5" xml:id="note_21321"/>
									</beam>
								</layer>
								<layer n="2" xml:id="layer_21282b">
									<mSpace tstamp="1" xml:id="mspace_21323"/>
								</layer>
							</staff>
							<staff n="3" xml:id="staff_21336">
								<layer n="1" xml:id="layer_21342">
									<beam xml:id="beam_21348">
										<note dots="1" dur="8" oct="3" pname="a" tstamp="1" xml:id="note_21354"/>
										<note dur="16" oct="3" pname="b" tstamp="1.75" xml:id="note_21360"/>
									</beam>
									<beam xml:id="beam_21369">
										<note accid.ges="s" dur="8" oct="4" pname="c" tstamp="2" xml:id="note_21375"/>
										<note dur="8" oct="3" pname="a" tstamp="2.5" xml:id="note_21381"/>
									</beam>
								</layer>
								<layer n="2" xml:id="layer_21342b">
									<mSpace tstamp="1" xml:id="mspace_21383"/>
								</layer>
							</staff>
							<staff n="4" xml:id="staff_21396">
								<layer n="1" xml:id="layer_21402">
									<mRest tstamp="1" xml:id="mRest_21408"/>
								</layer>
								<layer n="2" sameas="#layer_21402" xml:id="layer_21402b"/>
							</staff>
							<dir layer="1" place="above" staff="2" tstamp="1" xml:id="dir_21837">
								<rend fontstyle="normal" xml:id="rend_21837a">1 <rend rend="sup" xml:id="rend_21837">mo</rend>
								</rend>
							</dir>
							<slur endid="#note_21261" staff="1" startid="#note_21234" xml:id="slur_21849"/>
							<slur endid="#note_21321" staff="2" startid="#note_21294" xml:id="slur_21855"/>
							<slur endid="#note_21381" staff="3" startid="#note_21354" xml:id="slur_21861"/>
						</measure>
					</section>
				</score>
			</mdiv>
		</body>
	</music>
</mei>
```

### PR DESCRIPTION
**Pull request by rettinghaus**
closes #1399

### CODE REVIEW

**Comment by lpugin** [comment]
You also need to adjust iomei.h/cpp

**Comment by rettinghaus** [comment]
Good morning. Why or what?

**Comment by lpugin** [comment]
> Good morning. Why or what?

This does not make sense anymore, does it?
https://github.com/rism-ch/verovio/blob/1b598e1e5162cdb98feed58a848aff41eedb9d33/src/iomei.cpp#L4874

**Comment by lpugin** [comment]
> > Good morning. Why or what?
> 
> This does not make sense anymore, does it?
> 
> https://github.com/rism-ch/verovio/blob/1b598e1e5162cdb98feed58a848aff41eedb9d33/src/iomei.cpp#L4874

Sorry, my mistake. (I was confused because it was not there in the first place.)

**Comment by rettinghaus** [comment]
I'd say it does. I changed MSPACE not SPACE. There wasn't i/o for DurationInterface in the first place.

**Pull request merged**
