### PR TITLE
removing g containers in extracted glyphs

### PR DESCRIPTION
**Pull request by rettinghaus**
This update removes the unnecessary `<g>` container from the extracted glyphs putting the necessary `@transform` directly into the `<path>`, reducing the payload, resulting finally in smaller SVGs. 

The problem with the latest version of Bravura was, that it removed the needed `@font-family` from `<font-face>` and all `@glyph-name`.

### CODE REVIEW

**Comment by lpugin** [comment]
Good. Have you tested the result with several browsers?

**Comment by rettinghaus** [comment]
Yes. Chrome + Chromium, Firefox, IE, and other viewers. Works great!

**Comment by lpugin** [comment]
I tried to re-generate the font and there is still the problem with the Bravura. Could you revert it? Or we need to fix the issue but I am not sure I got what was changed.

**Comment by rettinghaus** [comment]
Coudn't figure the problem. Try Bravura 1.18, with this version it works fine (for me at least).

**Pull request merged**
