### PR TITLE
adding examples for fermatas and trills

### PR DESCRIPTION
**Pull request by rettinghaus**
This PR adds examples for fermatas and trills to the feature list. Yet the code snippets have to be extracted.

### CODE REVIEW

**Comment by lpugin** [comment]
Thanks. To extract the code snippets, you can try to go in `./examples/features` and run `./subtrees.sh`

**Comment by rettinghaus** [comment]
I thought, those shouldn't be committed?

**Comment by lpugin** [comment]
Yes, they have to.

**Comment by rettinghaus** [comment]
Here you go.

**Pull request merged**
