### PR TITLE
Fixes leak of elements of m_beamElementCoords array

### PR DESCRIPTION
**Pull request by valeriyvan**

### CODE REVIEW

**Comment by valeriyvan** [comment]
@Monceber, could you please have a look? I am not 100% sure if it's right way to fix leak. What I am sure about - `BeamElementCoord`'s are leaking.

**Comment by jspizziri** [comment]
@craigsapp any chance we could get these memory leak fixes released to a patch version?

**Comment by craigsapp** [comment]
How do I do that @lpugin?

**Comment by lpugin** [comment]
https://github.com/rism-ch/verovio/releases/tag/version-2.7.2

**Comment by jspizziri** [comment]
@lpugin thank you!

**Pull request merged**
